### ISSUE TITLE
Exception while generating mappers when using non existing field

### ISSUE THREAD

**Issue by mpachucki-decerto** [mapstruct/mapstruct#1177]
Hi,
while running mapstruct preprocessor I get this error, it is caused by a @Mapping that references a nonexisting field in target class

at java.util.ArrayList$Itr.next(ArrayList.java:854)  
at org.mapstruct.ap.internal.util.Collections.first(Collections.java:77)  
at org.mapstruct.ap.internal.model.NestedTargetPropertyMappingHolder$Builder.groupByTargetReferences(NestedTargetPropertyMappingHolder.java:288)  
at org.mapstruct.ap.internal.model.NestedTargetPropertyMappingHolder$Builder.build(NestedTargetPropertyMappingHolder.java:133)  
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.handleDefinedNestedTargetMapping(BeanMappingMethod.java:359)  
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.handleDefinedMappings(BeanMappingMethod.java:325)  
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:137)  
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:373)  
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)  
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)  
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:80)  
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)  
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)  
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)  
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  
at com.sun.tools.javac.main.Main.compile(Main.java:523)  
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  
at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.executeWithExceptionsHandled(AbstractAnnotationProcessorMojo.java:545)  
at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:285)  
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)  
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)  
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)  
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)  
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)  
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)  
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)  
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)  
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)  
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)  
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)  
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)  
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)  
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)  
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
at java.lang.reflect.Method.invoke(Method.java:497)  
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)  
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)  
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)  
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)  
at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by filiphr** [comment]
I think that this is  the same problem as in #1153. Can you show us your mapper?

**Comment by filiphr** [comment]
I just checked the exception is exactly the same. I will close this. You can track #1153 for the progress
