### ISSUE TITLE
ClassNotFoundException when running JUnit tests in eclipse using gradle example

### ISSUE THREAD

**Issue by masterky** [mapstruct/mapstruct#1214]
I'm not able to run the 'mapstruct-on-gradle' example project using junit 'Test' annotations in eclipse. The test fails with 'ClassNotFoundException: Cannot find implementation for ...SourceTargetMapper. 
I'm using javaSE-1.8, mapstruct 1.1.0.Final and JUnit 4.1.2

**Comment by filiphr** [comment]
We'll have to investigate why this does not work. Does a normal gradle build work for you there?

**Comment by masterky** [comment]
Yes it does. Is there something to bear in mind when using mapstruct with junit and gradle?

**Comment by filiphr** [comment]
I asked so we know where exactly the problem is. Have you tried running `gradle eclipse`? There shouldn't be anything special to junit and gradle. It looks like the mappers are not generated i.e. the annotation processor has not been invoked. 

@agudian is there something special that one needs to do for gradle and eclipse?

**Comment by masterky** [comment]
I did but the error still occurs.

**Comment by saeedansari** [comment]
I have same issue with Gradle and IntelliJIDEA. Mapper is generated and it is in the same package as the interface annotated with `@Mapper`.

**Comment by filiphr** [comment]
@saeedansari are you talking about the example our your own?

**Comment by rsknp9** [comment]
Hi,
I am having same issue. I performed the following steps.
1. Import mapstruct-on-gradle project as a gradle project in eclipse. (https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-on-gradle)
2. Changed the gradle version to 4.0.2 in build.gradle file.
3. Ran commands gradle clean and gradle build successfully.
4. Ran ConversionTest.java as a gradle test and getting following excepton:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at 
..............

5. Created a Test class with the following code 
	public static void main(String[] args) {
        Source source = new Source();
        source.setFoo(42);
        source.setBar(23L);
        source.setZip(73);
        
        Target target = SourceTargetMapper.INSTANCE.sourceToTarget(source);

        System.out.println();
        System.out.println(target.getFoo());
        System.out.println(target.getBar());
        System.out.println(target.getZip());
	}
6. When tried to run above class as a java application then getting following exception:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mapstruct.example.TestMap.main(TestMap.java:13)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for org.mapstruct.example.SourceTargetMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:79)
	at org.mapstruct.example.SourceTargetMapper.<clinit>(SourceTargetMapper.java:29)
	... 1 more
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for org.mapstruct.example.SourceTargetMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:93)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:76)
	... 2 more
Could you please help me to resolve this issue. I have tried other MapStruct examples with gradle but always getting java.lang.ClassNotFoundException: Cannot find implementation..exception

**Comment by sjaakd** [comment]
is this still an issue?

**Comment by BradPenwarden** [comment]
Still having similar issue with Eclipse Luna - Gradle 4.10 and the Eclipse JUnit runner.

Getting ClassNotFound : Cannot find implementation for ...(MappedClassName).

I see the generated source in my project/build/apt/generated & they are now also in my core class/com... directory. 

Unable to get Eclipse to find the generated source.

**Comment by filiphr** [comment]
This could be related to https://github.com/eclipse/buildship/issues/329
