### ISSUE TITLE
IndexOutOfBoundsException in Eclipse

### ISSUE THREAD

**Issue by samuelbr** [mapstruct/mapstruct#1258]
Hi,
I'm using Mapstruct 1.1.0.Final. Annotation processing finished with this exception:

```
Internal error in the mapping processor: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.mapstruct.ap.internal.model.MapMappingMethod.equals(MapMappingMethod.java:322)
	at java.util.ArrayList.indexOf(Unknown Source)
	at java.util.ArrayList.contains(Unknown Source)
	at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapMapping(PropertyMapping.java:627)
	at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:253)
	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:437)
	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:138)
	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:365)
	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:146)
	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:117)
	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:270)
	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:250)
	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:216)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:155)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:368)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:330)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:135)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)```

Thanks

**Comment by agudian** [comment]
Before we look into it in more detail: could you please chek if you still get the error with our latest version 1.2.0.CR1?

And thanks for the report! 👍

**Comment by agudian** [comment]
Oh and if you see that it fails with 1.2.0.CR1 as well, then please create a small self-contained example project (some bean types and the mapper are enough) that reproduces the bug so we can investigate.
My assumption would be that it has something to do with the declared type of a map-property in your bean class, something that maybe has the generics filled out (or maybe only partially?)...
We had a similar issue that was fixed in 1.1.0.Final: #853.

**Comment by samuelbr** [comment]
Hi @agudian 
I tried 1.2.0.CR1, but this version didn't correct this issue. So I prepared simplified example project with this issue: https://github.com/samuelbr/mapstruct-issue

Thanks.

**Comment by agudian** [comment]
Hmm, for me, the sample works with `1.2.0.CR1`, but I can see that it doesn't work for `1.1.0.Final`. 

Could you please post the StackTrace you get for `1.2.0.CR1` with your sample project?

**Comment by samuelbr** [comment]
I'm sorry `1.2.0.CR1` fix this issue. Probably eclipse didn't update versions when I tried new version. So `1.2.0.CR1` fix this issue. 

Thanks.
