### ISSUE TITLE
Internal error in the mapping processor with ADDER_PREFERRED on CollectionMapping

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1467]
I am not sure if the new SNAPSHOT was released and this bug appeared or it was before,
after successful ADDER_PREFERRED workaround to https://github.com/mapstruct/mapstruct/issues/1453 suddenly, with another mappings I get this one. So, if I go with other than ADDER_PREFERRED it generates wrong capture, otherwise this _)
```
19:37:20.161 [ERROR] [system.err] C:\path\MyMapper.java:16:
 error: Internal error in the mapping processor: java.util.NoSuchElementException       
 at java.base/java.util.ArrayList$Itr.next(ArrayList.java:896)  
 at org.mapstruct.ap.internal.util.Collections.first(Collections.java:77)       
 at org.mapstruct.ap.internal.model.common.Type.getAdderForType(Type.java:590)  
 at org.mapstruct.ap.internal.model.common.Type.getPropertyWriteAccessors(Type.java:513)        
 at org.mapstruct.ap.internal.model.source.TargetReference$BuilderFromTargetMapping.getTargetEntries(TargetReference.java:196)  
 at org.mapstruct.ap.internal.model.source.TargetReference$BuilderFromTargetMapping.build(TargetReference.java:164)     
 at org.mapstruct.ap.internal.model.source.Mapping.init(Mapping.java:367)       
 at org.mapstruct.ap.internal.model.source.Mapping.init(Mapping.java:337)       
 at org.mapstruct.ap.internal.model.source.SourceMethod$Builder.build(SourceMethod.java:203)    
 at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.getMethodRequiringImplementation(MethodRetrievalProcessor.java:271)    
 at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrievePrototypeMethods(MethodRetrievalProcessor.java:122)    
 at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:95)      
 at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:72)      
 at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)        
 at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)       
 at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  
 at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:158)        
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)   
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)     
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)     
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)      
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)   
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)       
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)   
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)  
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)         
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)    
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)      
 at org.gradle.api.internal.tasks.compile.IncrementalAnnotationProcessingCompileTask.call(IncrementalAnnotationProcessingCompileTask.java:76)   
 at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)      
 at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)      
 at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)      
 at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)      
 at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)      
 at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)      
 at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)      
 at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:44)      
 at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:28)      
 at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:50)  
 at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:36)  
 at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)   
 at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:126)      
 at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)      
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    
 at java.base/java.lang.reflect.Method.invoke(Method.java:564)  
 at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)   
 at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)  
 at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)  
 at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)  
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)       
 at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)   
 at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)   
 at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)        
 at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)     
 at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)       
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)       
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)       
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)      
 at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)    
 at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)  
 at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)        
 at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)      
 at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)         
 at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)    
 at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)    
 at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)  
 at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)        
 at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)      
 at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)        
 at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)      
 at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)      
 at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)   
 at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)   
 at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)        
 at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)     
 at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)       
 at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)    
 at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)    
 at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)       
 at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)        
 at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:667)  
 at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:600)  
 at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)      
 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)      
 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)       
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)   
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)   
 at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)       
 at java.base/java.lang.Thread.run(Thread.java:844)
```

N.B. This not NOT with custom naming strategy, just with regular one with exception of `! isAdder(..)`
e.g.
```
public class NamingStrategy extends DefaultAccessorNamingStrategy {
    private static final Pattern JAVA_JAVAX_PACKAGE = Pattern.compile( "^javax?\\..*" );

    @Override
    protected boolean isBuilderSetter(final ExecutableElement method) {
        return method.getParameters().size() == 1 &&
                !JAVA_JAVAX_PACKAGE.matcher(method.getEnclosingElement().asType().toString()).matches() &&
                !this.isAdderMethod(method) &&
                //TODO The Types need to be compared with Types#isSameType(TypeMirror, TypeMirror)
                method.getReturnType().toString().equals(method.getEnclosingElement().asType().toString());
    }
}
``` 
either way even if I simply put mapstruct 1.3.0-SNAPSHOT on classpath without any preventive actions like above, it gets the same error, so it obviously does not get to the poing where it matters. 
I didn't dig deep yet, so the is very superficial observation.
What do you need?

**Comment by soberich** [comment]
I found this https://github.com/mapstruct/mapstruct/issues/1153

**Comment by soberich** [comment]
`ADDER_PREFFERED` means "adder methods will be preferred over setter methods, **if** both are present for a given collection-typed property"
So I got 
```
error: Internal error in the mapping processor: java.util.NoSuchElementException         
 at java.base/java.util.ArrayList$Itr.next(ArrayList.java:896)  
 at org.mapstruct.ap.internal.util.Collections.first(Collections.java:77)       
 at org.mapstruct.ap.internal.model.common.Type.getAdderForType(Type.java:590)
```
Why is it in `org.mapstruct.ap.internal.util.Collections.java`
```

public static <T> T first(Collection<T> collection) {
        return collection.iterator().next();
                                 // ^NPE ?? (NoSuchElementException actually)
    }
```
so, here is the null I guess in
`org.mapstruct.ap.internal.model.common.Type#determineTypeArguments`

```
    public List<Type> determineTypeArguments(Class<?> superclass) {
        if ( qualifiedName.equals( superclass.getName() ) ) {
            return getTypeParameters();
        }

        List<? extends TypeMirror> directSupertypes = typeUtils.directSupertypes( typeMirror );
        for ( TypeMirror supertypemirror : directSupertypes ) {
            Type supertype = typeFactory.getType( supertypemirror );
            List<Type> supertypeTypeArguments = supertype.determineTypeArguments( superclass );
            if ( supertypeTypeArguments != null ) {
                return supertypeTypeArguments;
            }
        }

        return null;
                 ^ HERE
    }
```

case.
I don't have adders on one side but I have them at another side (say DTOs with builders and adders, but not Entities - they are plain POJOs). So, specifying ADDER_PREFFERED the expected behavior is WHEN there are adders - they invoked.  So, now no adders allowed since it does not compile, so I depend on locally built and installed #1465
Please, inform at least when that PR #1465 will be merged and available in repo as snapshot?

**Comment by soberich** [comment]
> I suspect that beea141 might be the issue. probably we need to get the adder based on the collection type. 
Yes and more It is more general.

Later I will post a link to example and also I consider to rename the issue. Other modifications, maybe splitting issue do them as you want, as this one I believe may span across many use cases. 
This Issue is all about **GENERICS**, and maybe **ABSTRACT parents** speaking closer to business functionality.
Having config and mapper as below we would have what's marked in the code. Please see.
```
@MapperConfig(
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG)
public interface AbstractMapperConfig {

    /*-------------------------------------------
    |                  1 4 6 7                   |
    ============================================*/
    // HERE! If uncomment one of @Mapping(..)
    //FIXME: java.util.NoSuchElementException  	at java.base/java.util.ArrayList$Itr.next
//    @Mapping(target = "id", source = "id")
//    AbstractEntity/*<?>*/ mapRaw(CommonDTO source);

    // FINE
    // FIXME: But it'l probably generate a useless/inappropriate mapping => see below
//    @Mapping(target = "id", source = "id")
//    AbstractEntity<?> mapWithUnboundWildcard(CommonDTO source);
    /*-------------------------------------------
    |                  1 4 6 7                   |
    ============================================*/

    //FIXME: This COMPILES (it should not maybe) but produces super weird output!
    //FIXME:
    //FIXME:    protected void longToAPK(Long long1, PK<A> mappingTarget) {
    //FIXME:        if ( long1 == null ) {
    //FIXME:            return;
    //FIXME:        }
    //FIXME:    }
    // TODO: Throw exception or smthing like that maybe.
//    @Mapping(target = "id", source = "id")
//    Identifiable mapIdentifiable(CommonDTO source);

    @Mapping(target = "id", source = "id.id")
    CommonDTO map(AbstractEntity/*<?>*/ source);
}
```
mapper 1
```
@Mapper(config = AbstractMapperConfig.class,
        collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED)
public interface AdderPrefferedMapper {

    /*-------------------------------------------
    |         ABSTRACT GENERIC PARENT            |
    ============================================*/
    // FIXME: error: Internal error in the mapping processor:
    // FIXME: java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
//    @Mapping(target = "id", source = "id.id")
//    CommonDTO mapRaw(AbstractEntity/*<?>*/ source);
    // FINE
    @Mapping(target = "id", source = "id.id")
    CommonDTO mapWithUnboundWildcard(AbstractEntity<?> source);
    /*-------------------------------------------
    |         ABSTRACT GENERIC PARENT            |
    ============================================*/
    //FIXME: These two become necessary only when ACCESSOR_ONLY used. Despite this (exact same) mapping logic generated with no problem when non-ACCESSOR_ONLY used.
    //FIXME:  why is this necessary then ??
    // TODO: Automatically generate as with ACCESSOR_ONLY maybe  ?
    Nested from(CommonDTO.NestedDTO nestedDTO);
    CommonDTO.NestedDTO from(Nested nested);
}

```
mapper 2
```
@Mapper(config = AbstractMapperConfig.class)
public interface RawCollectionGeneratingMapper {

    A mapA(CommonDTO dto);

    B mapB(CommonDTO dto);

    /*-------------------------------------------
    |            F O R B B I D  RAW              |
    ============================================*/
    //FIXME:  It COMPILES !
    //FIXME:  Generates RAW Collection and assignes inappropriate type
    //FIXME:  ...
    //FIXME:  List list = a.getNesteds();
    //FIXME:    if ( list != null ) {
    //FIXME:      commonDTO.setNesteds( new ArrayList<NestedDTO>( list ) );
    //FIXME:    }
    //FIXME:   ...
    //FIXME:   Solution is to add bound <?>
    //TODO:   Forbid Raw types?
    CommonDTO mapRaw(AbstractEntity/*<?>*/ a);

    // FINE
    CommonDTO mapWithUnboundWildcard(AbstractEntity<?> a);
    /*-------------------------------------------
    |            F O R B B I D  RAW              |
    ============================================*/
}
```

**Comment by filiphr** [comment]
@soberich thanks a lot for this detailed analysis and the example. We will have a look at it and try to fix all issues with it. Can we use the code you have written?

This are really some nice interesting edge cases with a lot of mixes of generics and abstracts. It's really difficult to think of such examples 😄

**Comment by soberich** [comment]
@filiphr thanks

> Can we use the code you have written?
of course

> See #1477. It is a bug
Great, means sometime it'll be fixed to get rid of those unnecessary methods.

**Comment by filiphr** [comment]
Thank you @soberich.

Yes #1477 will be fixed eventually, if not for 1.3.0.Beta1, then for sure for the one after that.

Btw I haven't fully analyzed all the issues, but the goal is to have them all analyzed and fixed asap

**Comment by filiphr** [comment]
I had a deeper look at some of the things. And it seems that the compiler is doing something strange. For example:

```java
class Scratch {
    public static void main(String[] args) {
        
        Foo foo = new Foo();
        List<Integer> numbers = foo.getNumbers();
    }
    
    public static class Foo<T> {
        public List<Integer> getNumbers() {
            return null;
        }
    }
}
```

You get warning on `foo.getNumber()` for unchecked assignment. This means that during the annotation processing when we get the return type for `getNumbers()` we get a raw list without any type parameters which leads to the exception. This is also the reason why we generate that wrong raw list snippet:

```
List list = a.getNesteds();
if ( list != null ) {
    commonDTO.setNesteds( new ArrayList<NestedDTO>( list ) );
}
```

Maybe safest for us would be to ignore mapping into / from raw types. However, I am not entirely sure how we can check that.

I am going to move this for 1.3.x as we might need some help from someone that is more familiar with the Java compiler intrinsics

**Comment by filiphr** [comment]
Some materials to read why this is not working:

* https://twitter.com/filiphr/status/994822499782287360
* https://stackoverflow.com/questions/17743406/why-does-a-java-generic-raw-class-erase-all-generics-to-object-when-type-paramet
* https://stackoverflow.com/questions/11007723/combining-raw-types-and-generic-methods
* https://stackoverflow.com/questions/662191/why-wont-this-generic-java-code-compile

@agudian replied on my tweet:

>On raw type usages, all generics are dropped - even those with fixed bounds.

**Comment by filiphr** [comment]
The problems with the exception have been fixed.

The problems with the raw generics cannot be fixed due to the way the Java compiler works. We are using the compiler to get the information about the types, if this information is missing then there is nothing that MapStruct can do.

I am going to suggest not to use raw generics and use generics with wildcards instead. That way the compiler doesn't lose any information.
