### ISSUE TITLE
NullPointerException when building on OpenJDK 11

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1675]
Just tried to build MapStruct on OpenJDK 11.0.1 and am getting this exception:

```
Caused by: java.lang.NullPointerException
	at net.java.dev.hickory.prism.internal.PrismGenerator.getPrismName(PrismGenerator.java:122)
	at net.java.dev.hickory.prism.internal.PrismGenerator.process(PrismGenerator.java:108)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:888)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1214)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1326)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	... 28 more
```

Is this a known issue, @filiphr?

**Comment by filiphr** [comment]
Yes this is a known issue. I have a branch locally that I've been playing with building MapStruct with Java 9+. The NPE is due to the https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/prism/PrismGenerator.java#L65-L66 (my theory) and xml not being present.

Unfortunately, the branch I have is on my computer which is not with me in the moment, and I can't push it.

**Comment by filiphr** [comment]
I forgot to mention, MapStruct works with all Java 9+ versions. At least the mapstruct-examples are passing, see https://travis-ci.org/mapstruct/mapstruct-examples.

**Comment by gunnarmorling** [comment]
> and xml not being present.

Yes, I've arrived at the same conclusion. So we'd have to explicitly add the JAXB dependencies in a profile when running the build on JDK 11 or later.
