### ISSUE TITLE
Qualifier does not exist but compilation work

### ISSUE THREAD

**Issue by alexandrepetrillo** [mapstruct/mapstruct#1761]
- [ ] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by sjaakd** [comment]
according your description it sounds like a duplicate of #1714 Could you try and build the pull request and see if this solves your problem?

**Comment by alexandrepetrillo** [comment]
> according your description it sounds like a duplicate of #1714 Could you try and build the pull request #1739 and see if this solves your problem?

Yes i verified, mapstruct report me an error if the qualified mapping method doesn't exists.
thanks for your response.

But i have an error when using 1.4.0-SNAPSHOT when i use external config:



`
import org.mapstruct.Mapper;
import org.mapstruct.MapperConfig;


@MapperConfig
interface UsualConfig {
}

@Mapper(config = UsualConfig.class)
public interface FooMapperMapper {

}`


`[ERROR] ...FooMapperMapper.java:[12,7] error: Internal error in the mapping processor: java.lang.NullPointerException  	at java.util.ArrayList.addAll(ArrayList.java:577)  	at org.mapstruct.ap.internal.util.MapperConfiguration.imports(MapperConfiguration.java:104)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getExtraImports(MapperCreationProcessor.java:261)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:174)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:120)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:74)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:293)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:273)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:161)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	at com.sun.tools.javac.main.Main.compile(Main.java:523)  	at com.sun.tools.javac.main.Main.compile(Main.java:381)  	at com.sun.tools.javac.main.Main.compile(Main.java:370)  	at com.sun.tools.javac.main.Main.compile(Main.java:361)  	at com.sun.tools.javac.Main.compile(Main.java:74)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:497)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:597)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcessWithProperClassloader(JavacCompiler.java:578)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:567)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:178)  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:497)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)  	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:497)  	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
`

**Comment by sjaakd** [comment]
> But i have an error when using 1.4.0-SNAPSHOT when i use external config:

Hmm. that's not so nice.. And that happens only using this PR? Or with 1.3 in general? The place in where you get the error seems to be unrelated to the problems solved, so I think we might be dealing with another issue. To be short, either:

1. I need to do something in my fix if this is causing he issue.
2. Or: We need another Issue / PR to solve your problem

Could you help me by attach / point me to a branch / gist with a reproducer?

**Comment by filiphr** [comment]
Thanks for trying it out @alexandrepetrillo.

@sjaakd I think that the problem is due to the changes for #1453. It seems that the config prism doesn't work well when the interface annotated with `@MapperConfig` is in another jar. I think that we can try this only be creating an integration test with multiple modules.

@sjaakd should we close this issue and open a new one for the exception?

**Comment by sjaakd** [comment]
> @sjaakd should we close this issue and open a new one for the exception?

If its related to #1453 we should. But lets await the answer of @alexandrepetrillo (and a reproducer).. Saves work :smile:
