### ISSUE TITLE
Using constructor as builderCreationMethod in custom builder provider causes NullPointerException

### ISSUE THREAD

**Issue by dengzhizhi** [mapstruct/mapstruct#1801]
I am building a custom builder provider and using constructor as the builderCreationMethod.

Something like

```java
        List<TypeElement> types = ElementFilter.typesIn(typeElement.getEnclosedElements());
        List<BuilderInfo> builderInfo = new ArrayList<>();
        types.stream()
             .filter(t -> !this.typeUtils.isSameType(t.asType(), typeElement.asType()))
             .filter(innerType -> isPossibleInnerBuilder(innerType, typeElement))
             .forEach(innerBuilderClass -> {
                 Collection<ExecutableElement> buildMethods = findBuildMethods(innerBuilderClass, typeElement);
                 if (!buildMethods.isEmpty()) {
                     ElementFilter.constructorsIn(innerBuilderClass.getEnclosedElements())
                                  .stream()
                                  .filter(constructor -> constructor.getParameters().isEmpty())
                                  .findAny()
                                  .ifPresent(defaultConstructor -> builderInfo.add(
                                      new BuilderInfo.Builder()
                                          .builderCreationMethod(defaultConstructor)
                                          .buildMethod(buildMethods)
                                          .build()
                                  ));
                 }
             });
```

It will cause NPE during code generation

```java
error: Internal error in the mapping processor: java.lang.NullPointerException

at org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:99)    
at org.mapstruct.ap.internal.util.Executables.getAllEnclosedAccessors(Executables.java:136)     
at org.mapstruct.ap.internal.model.common.Type.getAllAccessors(Type.java:647)   
at org.mapstruct.ap.internal.model.common.Type.getPropertyReadAccessors(Type.java:508)          
at org.mapstruct.ap.internal.model.source.TargetReference$BuilderFromTargetMapping.getTargetEntries(TargetReference.java:189)   
at org.mapstruct.ap.internal.model.source.TargetReference$BuilderFromTargetMapping.build(TargetReference.java:158)      
at org.mapstruct.ap.internal.model.source.Mapping.init(Mapping.java:446)        
at org.mapstruct.ap.internal.model.source.Mapping.init(Mapping.java:413)        
at org.mapstruct.ap.internal.model.source.SourceMethod$Builder.build(SourceMethod.java:197) 
```

I did a very brief investigation, the direct cause is in the `BuilderType::create` method when the `builder` in `BuilderType` is initialized. For constructor, the return type is `void`. I think it should use the `owner type` when the `builderCreationMethod` is a constructor. 

```java
    public static BuilderType create(BuilderInfo builderInfo, Type typeToBuild, TypeFactory typeFactory,
        Types typeUtils) {
        if ( builderInfo == null ) {
            return null;
        }

        // The following line won't work for constructor method because the return type of a constructor is 'void'. 
        Type builder = typeFactory.getType( builderInfo.getBuilderCreationMethod().getReturnType() );

        ExecutableElement builderCreationMethod = builderInfo.getBuilderCreationMethod();
        Type owner;
        TypeMirror builderCreationOwner = builderCreationMethod.getEnclosingElement().asType();
        if ( typeUtils.isSameType( builderCreationOwner, typeToBuild.getTypeMirror() ) ) {
```

**Comment by filiphr** [comment]
Thanks for reporting this @dengzhizhi.

Seems like you have already went deep into the MapStruct code. Would you be willing to provide a fix for this bug?

**Comment by dengzhizhi** [comment]
Hi @filiphr 

Please see my pull request. I have tested locally with my custom builder provider. I am happy to provide the builder provider and some unit tests if you like, but I'll need your guidance on where to put them.

**Comment by 51systems** [comment]
I ran into this same problem today. It seems like development on the pull request has stalled. Any update on this?

**Comment by sjaakd** [comment]
@51systems @dengzhizhi  I'll have a look as well

**Comment by sjaakd** [comment]
fixed by PR.. @dengzhizhi thanks for your help
