### ISSUE TITLE
Infinite Stack Trace Loop for Invocation Exception with Abstract Mapper

### ISSUE THREAD

**Issue by IDoCodingStuffs** [mapstruct/mapstruct#1819]
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at org.mapstruct.factory.Mappers.doGetMapper(Mappers.java:85)
        at org.mapstruct.factory.Mappers.getMapper(Mappers.java:69)
        at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58)
        at com.____.OutboundRequestMapper.<init>(OutboundRequestMapper.java:19)
        at com.______.OutboundRequestMapperImpl.<init>(OutboundRequestMapperImpl.java:28)
        at jdk.internal.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at org.mapstruct.factory.Mappers.doGetMapper(Mappers.java:85)
        at org.mapstruct.factory.Mappers.getMapper(Mappers.java:69)
        at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58)
...
Same lines just keep repeating until memory is full
...
`

The line 19 for the OutboundRequestMapper is this:

`  OutboundRequestMapper INSTANCE = Mappers.getMapper(OutboundRequestMapper.class);
`
The line mentioned for the Impl class is just the class declaration itself. The rest are all from default libraries.

**Comment by IDoCodingStuffs** [comment]
Removing the self referring INSTANCE takes care of the problem. So either those should not be allowed inside abstract mappers or whatever is causing the invocation exception should be fixed.

**Comment by sjaakd** [comment]
So.. without any code your issue is a bit hard to grasp.. Can you add some reproducer?

**Comment by IDoCodingStuffs** [comment]
`
@Mapper(componentModel = "spring")
public abstract class OutBoundRequestMapper implements .../*interfaces with some mappings*/... {
  OutboundRequestMapper INSTANCE = Mappers.getMapper(OutboundRequestMapper.class);

  public abstract Object map(Object source);
}
`

Run `mvn install` to reproduce

**Comment by sjaakd** [comment]
`OutboundRequestMapper INSTANCE = Mappers.getMapper(OutboundRequestMapper.class)` should be used when you don't have a DI framework like Spring or CDI (referred to in the documentation as the default component model). Although the [documentation](http://mapstruct.org/documentation/stable/reference/html/#retrieving-mapper) is perhaps not too clear, the examples are.

Let me know if the documentation is clear. If not, let us know of alternatively file a PR to enhance it..

I'm going to close this issue as it is documented.

**Comment by chris922** [comment]
> `OutboundRequestMapper INSTANCE = Mappers.getMapper(OutboundRequestMapper.class)` should be used when you don't have a DI framework like Spring or CDI

You mean `public static OutboundRequestMapper INSTANCE = Mappers.getMapper(OutboundRequestMapper.class)` ?

In an (abstract) class the variable must be declared as static, otherwise it will be evaluated everytime the class will be instantiated.
