### ISSUE TITLE
ImmutableBuilderProvider gets stuck in an infinite recursion if there is no builder

### ISSUE THREAD

**Issue by facboy** [mapstruct/mapstruct#1934]
If you have a class with `@Value.Immutable(builder = false)` so that Immutables creates a basic factory method, `ImmutableBuilderProvider` recurses infinitely and fails with a `StackOverflowError`.  The problem is that 

- it finds the `Immutable` annotation on the parent class `Obj`
- searches for and finds the `ImmutableObj` class
- searches for and fails to find a `possible builder method` on the `ImmutableObj` class
- falls back to finding a builder on the parent class `Obj`
- finds the `Immutable` annotation on `Obj`

and so on

```
...
    at org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:185)
    at org.mapstruct.ap.spi.ImmutablesBuilderProvider.findBuilderInfoForImmutables(ImmutablesBuilderProvider.java:58)
    at org.mapstruct.ap.spi.ImmutablesBuilderProvider.findBuilderInfo(ImmutablesBuilderProvider.java:40)
    at org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:96)   at org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:185)
    at org.mapstruct.ap.spi.ImmutablesBuilderProvider.findBuilderInfoForImmutables(ImmutablesBuilderProvider.java:58)
    at org.mapstruct.ap.spi.ImmutablesBuilderProvider.findBuilderInfo(ImmutablesBuilderProvider.java:40)
    at org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:96)
    at org.mapstruct.ap.spi.DefaultBuilderProvider.findBuilderInfo(DefaultBuilderProvider.java:185)
...
```

**Comment by sjaakd** [comment]
@facboy can you provide a PR to fix this & a reproducer?

**Comment by facboy** [comment]
I won't have time to do this for at least a couple of months.
