### ISSUE TITLE
JAVA 11 mapstruct-processor throws

### ISSUE THREAD

**Issue by chenziliang** [mapstruct/mapstruct#1942]
- [ ] Is this an issue (and hence not a question)? 
Probably not.

In JDK11, the Mapping processor can't locate the `javax.xml.*` 3rd party packages for which i have specified for my project in Gradle file. As we know, `javax.xml.*` has been removed from JAVA 11, so i specified the dependencies in the Gradle project file. However, look like mapping processor plugin also depends on `javax.xml.*` and can't find it during it processing of the mapping. My question is how to specify the classpath for the `mapstruct-processor` in Gradle ? Thanks so much.

Stack trace thrown is as below.
```
error: Internal error in the mapping processor: java.lang.           NoClassDefFoundError: javax/xml/bind/JAXBElement
 at org.mapstruct.ap.internal.model.source.builtin.JaxbElemToValue.<init>(JaxbElemToValue.java:41)
 at org.mapstruct.ap.internal.model.source.builtin.BuiltInMappingMethods.<init>(BuiltInMappingMethods.java:49)
 at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.<init>(MappingResolverImpl.java:99)
 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:98)
 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76)
 at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:270) 
```

**Comment by chenziliang** [comment]
Ok, upgrading to 1.3.1 for the processor resolves the problem. Close this question.

**Comment by edgarLsanchez** [comment]
Thank you.  It works for me, with the 1.3.1.Final version for mapstruct-processor artifact
