### ISSUE TITLE
Nullptr as result of #2101 implementation

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#2139]
See: https://github.com/mapstruct/mapstruct/pull/2140

Internal error in the mapping processor: java.lang.NullPointerException                at java.lang.String.startsWith(String.java:1405)  at java.lang.String.startsWith(String.java:1434)       at org.mapstruct.ap.internal.model.source.MappingMethodOptions.elementsAreContainedIn(MappingMethodOptions.java:241)                at org.mapstruct.ap.internal.model.source.MappingMethodOptions.isRedefined(MappingMethodOptions.java:233)                at org.mapstruct.ap.internal.model.source.MappingMethodOptions.addAllNonRedefined(MappingMethodOptions.java:223)                at org.mapstruct.ap.internal.model.source.MappingMethodOptions.applyInheritedOptions(MappingMethodOptions.java:203)                at org.mapstruct.ap.internal.processor.MapperCreationProcessor.mergeInheritedOptions(MapperCreationProcessor.java:463)

**Comment by sjaakd** [comment]
Solved by PR
