### ISSUE TITLE
Internal error in the mapping processor: java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by danny-su** [mapstruct/mapstruct#2149]
When use both  **@BeanMapping(ignoreByDefault = true)  and  @Mapping(source = "xxxx", target = ".")**, there will be an error like the following: 
Error:(10,8) java: Internal error in the mapping processor: java.lang.ArrayIndexOutOfBoundsException: 0
  	at org.mapstruct.ap.internal.model.source.MappingMethodOptions.lambda$applyIgnoreAll$0(MappingMethodOptions.java:266)
  	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  	at java.util.Iterator.forEachRemaining(Iterator.java:116)
  	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
  	at org.mapstruct.ap.internal.model.source.MappingMethodOptions.applyIgnoreAll(MappingMethodOptions.java:267)
  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.mergeInheritedOptions(MapperCreationProcessor.java:489)
  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:283)
  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:151)
  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:122)
  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:74)
  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:338)
  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:318)
  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)
  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289) 
 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
  	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by filiphr** [comment]
We probably should not have an exception here.

However, the combination of `@BeanMapping(ignoreByDefault = true)` and `@Mapping(source = "xxxx", target = ".")` is a bit weird. You are saying that you want to ignore all properties, but actually you want name based mapping between the specific source and the target.

Why don't you define a method between `xxxx` and the target then?

We will fix the exception, but most likely it will be to not allow using `ignoreByDefault` when the `target` is `.`.

**Comment by filiphr** [comment]
>We will fix the exception, but most likely it will be to not allow using `ignoreByDefault` when the `target` is `.`.

While doing the fix I realised that we can actually do better and still apply the target this and ignore the rest

**Comment by filiphr** [comment]
>While doing the fix I realised that we can actually do better and still apply the target this and ignore the rest

In the end we decided to disallow using the combination due to the complexity of the fix to make it work.
