### ISSUE TITLE
Internal error in the mapping processor: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by michalkochanowicz** [mapstruct/mapstruct#2154]
- [X] Is this an issue (and hence not a question)? 

Version 1.3.1.Final.

Such a simple mapper...

```
@Mapper
public interface DocumentMapper {

	@Mapping(target = ".", source = "subDocument.subSubDocument")
	DocumentDTO documentToDocumentDTO(document document);

}
```

...causes an internal error:

```
Error:(11,8) java: Internal error in the mapping processor: java.util.NoSuchElementException
at java.util.ArrayList$Itr.next(ArrayList.java:862)
at org.mapstruct.ap.internal.util.Collections.first(Collections.java:50)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.handleDefinedMappings(BeanMappingMethod.java:477)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:184)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:376)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:151)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:122)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:283)
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:263)
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:221)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:156)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
at com.sun.tools.javac.main.Main.compile(Main.java:523)
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Source  classes are generated from WSDL and have quite complex structure.

**Comment by filiphr** [comment]
Thanks for the issue.

Can you please try with 1.4.0.Beta2? We have done some changes in the internal API in that are and it might work properly now. We also have some test cases for nested sources and mapping to `.`.

**Comment by sjaakd** [comment]
@michalkochanowicz you can always reopen if you think closing is  unjust or you have additional info

**Comment by hdeweirdt** [comment]
@filiphr I had a similar issue after trying out what I read  #1686. When I tried it using 1.3.1, going from the composition-based object to inheritance-based object worked but not the other way around. On 1.4.0.Beta2 this does work :)
