### ISSUE TITLE
Stack Trace instead of Message on Missing Mapping 

### ISSUE THREAD

**Issue by martin-mfg** [mapstruct/mapstruct#2263]
If mapstruct is unable to map a property, in version `1.3.1.Final` it reports: 
> "Can't map property "[...]" to "[...]". Consider to declare/implement a mapping method: "[...]".

Since version `1.4.0.Final` however a big and less helpful stacktrace is reported instead:

> /mapstruct-demo/src/main/java/org/example/DemoMapper.java:[6,8] Internal error in the mapping processor: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0      
at java.util.ArrayList.rangeCheck(ArrayList.java:653)    
at java.util.ArrayList.get(ArrayList.java:429)          
at org.mapstruct.ap.internal.model.common.Type$TypeVarMatcher.visitDeclared(Type.java:1165)     
at org.mapstruct.ap.internal.model.common.Type$TypeVarMatcher.visitDeclared(Type.java:1141)      
at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:936)        
at javax.lang.model.util.AbstractTypeVisitor6.visit(AbstractTypeVisitor6.java:92)        
at org.mapstruct.ap.internal.model.common.Type.resolveTypeVarToType(Type.java:1136)     
at org.mapstruct.ap.internal.model.source.builtin.BuiltInMethod.matches(BuiltInMethod.java:70)          
at org.mapstruct.ap.internal.model.source.selector.TypeSelector.lambda$getMatchingParameterBinding$0(TypeSelector.java:158)      
at org.mapstruct.ap.internal.model.source.selector.TypeSelector$$Lambda$82/14814827.test(Unknown Source)        
at java.util.ArrayList.removeIf(ArrayList.java:1405)    
at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingParameterBinding(TypeSelector.java:157)      
at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingMethods(TypeSelector.java:71)         
at org.mapstruct.ap.internal.model.source.selector.MethodSelectors.getMatchingMethods(MethodSelectors.java:62)          
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getBestMatch(MappingResolverImpl.java:452)          
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:263)   
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:158)   
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:139)    
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:243)       
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1236)          
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1200)        
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:269)          
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:378)       
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)      
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)         
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:74)         
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:338)         
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:318)         
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)   
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)          
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)         
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)    
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)    
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)     
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)         
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)      
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)         
at com.sun.tools.javac.main.Main.compile(Main.java:523)         
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)          
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)   
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)   
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)      
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)         
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)         
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)    
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)       
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)      
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)       
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)     
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)       
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)        
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)       
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)       
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)       
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)          
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)     
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)      
at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)         
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)          
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)         
at java.lang.reflect.Method.invoke(Method.java:497)     
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)   
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)          
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)        
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

I guess the previous behaviour is preferable.

For reference I uploaded a demo project that generates the shown stack trace to https://github.com/martin-mfg/mapstruct-demo. Simply run `mvn clean package` there.

**Comment by filiphr** [comment]
I agree that the stacktrace error is not nice to have. 

I checked out your project and run `mvn clean package` and indeed there is a problem on Java 8. When compiling with Java 11 everything is OK.

We will check why this is happening and why our tests haven't caught this problem.

Some more information, I tried changing `Object` to `Thread` and it worked correctly (it gave a nice error message).

Is this exception happening in your project for mapping between non `Object` class?

**Comment by filiphr** [comment]
The same problem occurs on Java 11 when `java.xml` is present.

The reason for the exception is when an erased type is assignable to Object.

Thanks a lot for the reproducible report @martin-mfg it helped tremendously to locate the problem.

**Comment by martin-mfg** [comment]
It's probably not necessary anymore, but I wanted to confirm anyway:
Yes, I am using Java 8. And if I switch from `Object` to `Thread` I do indeed get a nice error message.
Thanks for fixing this so quickly!
