### ISSUE TITLE
Internal error in the mapping processor: java.lang.RuntimeException: Fallback implementation of asMemberOf didn't work for null in CustomerDto

### ISSUE THREAD

**Issue by IronAdventures** [mapstruct/mapstruct#2374]
- [x] Is this an issue (and hence not a question)? 

### Versions

- Mapstruct: 1.4.2.Final
- Java: Java 16 RC (OpenJDK Runtime Environment (build 16+36-2231))
- Maven: 3.6.3

### Issue

Hi everyone,

I'm tinkering around with Mapstruct and Java 16.  I started with the mapstruct-record example in the examples repositories ([example](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-record)) which works like a charm. But as soon as I move the `CustomerDto` record into a different project and add it through a dependency I get the following error:

```java
Internal error in the mapping processor: java.lang.RuntimeException: Fallback implementation of asMemberOf didnt work for null in CustomerDto
at org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.asMemberOf(SpecificCompilerWorkarounds.java:134)
at org.mapstruct.ap.internal.util.workarounds.TypesDecorator.asMemberOf(TypesDecorator.java:135)
at org.mapstruct.ap.internal.util.Filters.getWithinContext(Filters.java:148)
at org.mapstruct.ap.internal.util.Filters.getReturnType(Filters.java:119)
at org.mapstruct.ap.internal.util.Filters.recordAccessorsIn(Filters.java:105)
at org.mapstruct.ap.internal.model.common.Type.getPropertyReadAccessors(Type.java:534)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:243)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:378)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:74)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:338)
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:318)
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1025)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:940)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1269)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1384)
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1261)
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:935)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
at org.codehaus.classworlds.Launcher.main(Launcher.java:47)  Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Symbol.getEnclosingElement()" because "sym" is null
at jdk.compiler/com.sun.tools.javac.model.JavacTypes.asMemberOf(JavacTypes.java:298)
at org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.asMemberOf(SpecificCompilerWorkarounds.java:120)  	... 51 more
```

I tried to debug the issue and the only information I could gather so far is, that the `element` parameter passed to the following function in the `SpecificCompilerWorkarounds` class, is always null for the `CustomerDto` record if it is added through the dependency:

```java
    static TypeMirror asMemberOf(Types typeUtils, ProcessingEnvironment env, VersionInformation versionInformation,
                                 DeclaredType containing, Element element) {
        TypeMirror result = null;
        Exception lastException = null;
        try {
            try {
                result = typeUtils.asMemberOf( containing, element );
            }
            catch ( IllegalArgumentException e ) {
                lastException = e;
                if ( versionInformation.isEclipseJDTCompiler() ) {
                    result = EclipseClassLoaderBridge.invokeAsMemberOfWorkaround( env, containing, element );
                }
            }
        }
        catch ( Exception e ) {
            lastException = e;
        }

        if ( null == result ) {
            throw new RuntimeException( "Fallback implementation of asMemberOf didn't work for "
                + element + " in " + containing, lastException );
        }

        return result;
    }
```

Since it is working as long as the record is in the same project, it seems that some information is lost if it is added through a dependency. Based on that I'm not sure if it is a real issue or if I messed up my project setup.

I added the setup below.

#### CustomerDto Project
record
```java
import java.util.UUID;

public record CustomerDto(UUID uuid, String name, boolean active) {
}
```
maven
```xml
  <groupId>org.example</groupId>
  <artifactId>untitled1</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

      <maven.compiler.source>16</maven.compiler.source>
      <maven.compiler.target>16</maven.compiler.target>
      <maven.compiler.release>16</maven.compiler.release>
  </properties>
```

#### Mapper Project
entity
```java
import java.util.UUID;

public class CustomerEntity {

    private UUID identifier;

    private String name;
    private boolean active;

    public CustomerEntity(UUID identifier,  String name, boolean active)
    {
        this.identifier = identifier;
        this.name = name;
        this.active = active;
    }

   // Getters and Setters
}
```

mapper
```java
@Mapper
public interface CustomerMapper {

    CustomerMapper INSTANCE = Mappers.getMapper(CustomerMapper.class);

    @Mapping(target = "identifier", source = "uuid")
    CustomerEntity fromRecord(CustomerDto record);

    @InheritInverseConfiguration
    CustomerDto toRecord(CustomerEntity entity);

}
```

maven
```xml
<groupId>org.example</groupId>
    <artifactId>untitled</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
        <maven.compiler.release>16</maven.compiler.release>

        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
    </properties>


    <dependencies>

        <dependency>
            <groupId>org.example</groupId>
            <artifactId>untitled1</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>

                    <source>16</source>
                    <target>16</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by filiphr** [comment]
I think that this is the same as #2294.

>Since it is working as long as the record is in the same project, it seems that some information is lost if it is added through a dependency. Based on that I'm not sure if it is a real issue or if I messed up my project setup.

It is actually none of that. It is a bug in the JDK. See [JDK-8258535](https://bugs.openjdk.java.net/browse/JDK-8258535). I am not keen on adding some custom handling here. Therefore, I would rather wait for Java to fix this bug. If they do not do this for Java 17 (the next LTS release) we will need to have another iteration of this.

**Comment by IronAdventures** [comment]
Thank you very much for the information.

I actually did not check for a JDK bug before opening the issue here, I'm sorry for that.

**Comment by filiphr** [comment]
>I actually did not check for a JDK bug before opening the issue here, I'm sorry for that.

No need to be sorry. Usually you will never expect that such an issue can be due to a JDK bug 😄. I personally was surprised when I figured it out.

**Comment by benvxavier** [comment]
worked for me, I had to separate the interface classes and implementations of the same package
