### ISSUE TITLE
Internal error in the mapping processor with InheritConfiguration when upgrading from 1.3.1.Final to 1.4.2.Final

### ISSUE THREAD

**Issue by tony-ts** [mapstruct/mapstruct#2409]
Hello!
I have the following snippet that works on 1.3.1.Final but doesn't with version 1.4.2.Final
What can be the reason for such an error?

```java
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}

@Mapper(config = ParentMapper.class)
interface ChildMapper {

    @Mappings({
            @Mapping(target = "requestId", expression = "java(java.util.UUID.randomUUID().toString())")
    })
    @InheritConfiguration
    ChildExampleDto toDto(ExampleEntity entity);

}

@Mapper
interface ParentMapper {

    ParentExampleDto toDto(ExampleEntity entity);

}

class ExampleEntity {
    private Long id;

}

class ChildExampleDto extends ParentExampleDto {

    private String requestId;

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }
}

class ParentExampleDto {
    private String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}

```

<details><summary>Exception stacktrace</summary>
<p>

```java
Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.model.source.MapperConfigOptions.uses(MapperConfigOptions.java:46)  	at org.mapstruct.ap.internal.model.source.MapperOptions.uses(MapperOptions.java:76)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetrievalProcessor.java:178)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:106)  	at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:65)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:338)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:318)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	at com.sun.tools.javac.main.Main.compile(Main.java:523)  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)  	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

</p>
</details>

Best regards

**Comment by MaestracciDamien** [comment]
Hey, I have the same issue, any workaround ?
