### ISSUE TITLE
With wrong config like Enum[] to String， the mapping processor throw NPE

### ISSUE THREAD

**Issue by Colorul** [mapstruct/mapstruct#2439]
- issue
With wrong config like Enum[] to String， the mapping processor throw NPE.
Mapper code：
```
@Mapper
public interface LiveMapper {
    LiveMapper INSTANCE = Mappers.getMapper(LiveMapper.class);
    @Mappings({
             @Mapping(target = "statusName", source = "status.desc"), 
            @Mapping(target = "modeName", source = "mode.desc") 
    })
    LiveVo from(Live entity);
}

```

LiveVo code：
```
public class LiveVo {
    private LiveMode[] mode;  
    private String modeName;  
    private LiveStatus status;  
    private String statusName;  
}  
```

Live coe：
```
public class Live{
    private LiveMode[] mode;
    private LiveStatus status;
}
```

version：
    mspstruct：1.3.1.Final
    processor：1.2.0.Beta2
NPE info：
`java: Internal error in the mapping processor: 
java.lang.NullPointerException  	
at org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:99)  	
at org.mapstruct.ap.internal.util.Executables.getAllEnclosedExecutableElements(Executables.java:99)  	
at org.mapstruct.ap.internal.model.common.Type.getAllMethods(Type.java:633)  	
at org.mapstruct.ap.internal.model.common.Type.getPropertyReadAccessors(Type.java:496)  	
at org.mapstruct.ap.internal.model.source.SourceReference$BuilderFromMapping.getSourceEntries(SourceReference.java:210)  	
at org.mapstruct.ap.internal.model.source.SourceReference$BuilderFromMapping.build(SourceReference.java:155)  	
at org.mapstruct.ap.internal.model.source.Mapping.init(Mapping.java:436)  	
at org.mapstruct.ap.internal.model.source.Mapping.init(Mapping.java:413)  	
at org.mapstruct.ap.internal.model.source.SourceMethod$Builder.build(SourceMethod.java:200)  	
at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.getMethodRequiringImplementation(MethodRetrievalProcessor.java:261)  	
at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.getMethod(MethodRetrievalProcessor.java:188)  	
at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetrievalProcessor.java:143)  	
at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:85)  	
at org.mapstruct.ap.internal.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:59)  	
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:283)  	
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:263)  	
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:221)  	
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:156)  	
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	
at com.sun.tools.javac.main.Main.compile(Main.java:523)  	
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  	
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  	
at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:207)  	
at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:491)  	
at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:343)  	
at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:268)  	
at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:221)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1448)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1126)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1193)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1087)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:853)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:443)  	
at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:184)  	
at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:135)  	
at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)  	
at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:127)  	
at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)  	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  	
at java.lang.Thread.run(Thread.java:748)  `

**Comment by filiphr** [comment]
First thing about:

>mapstruct：1.3.1.Final
>processor：1.2.0.Beta2

You should always use the same mapstruct and mapstruct-processor versions 😉 .

Have you tried this with the latest 1.4.2.Final version of the processor?

**Comment by filiphr** [comment]
I managed to reproduce the error. There is a PR for improving the error message and not throwing an exception by MapStruct
