### ISSUE TITLE
Mapping of value classes (Kotlin) not possible: "Person does not have an accessible constructor"

### ISSUE THREAD

**Issue by mcarleio** [mapstruct/mapstruct#2754]
When you use value classes in Kotlin, Mapstruct will fail to generate the mapping code due to inaccessible constructor.

### Steps to reproduce
To reproduce, simply use the [mapstruct-kotlin maven project in mapstruct-examples](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-kotlin) and do the following:
1. Create a value class:
   ```
   @JvmInline
   value class PersonId(val id: String)
   ```

2. Add it to Person class:
   ```
   data class Person(
       var id: PersonId?,
      // ...
   )
   ```
3. Call `mvn package`

### Expected output
A valid and working mapper.

### Actual Output
`error: Person does not have an accessible constructor`

### Example project
I created a fork and added a commit to showcase this: https://github.com/mcarleio/mapstruct-examples/commit/2277fb5171645b47158ff797db747eb1707fd7a1

**Comment by stravag** [comment]
This is a bummer... any updates on this issue?

**Comment by MarkWilsoncom** [comment]
**Bump**

**Comment by kimchanjung** [comment]
i have the same problem too

**Comment by droar** [comment]
No updates on this?

**Comment by mbannikov** [comment]
Same problem. Is there any bypass?

**Comment by mcarleio** [comment]
I have not found any solution with MapStruct yet, beside not using value classes.

But you can try out https://github.com/mcarleio/konvert instead. It uses KSP to generate mapping code in Kotlin during compilation and can handle value classes (and also java classes). It is not as powerful as MapStruct, but it is already working great for the projects I am using it in.

**Comment by wikeAtGH** [comment]
Has anyone any idea what would be necessary to fix this issue. Maybe someone is able to provide the fix.

**Comment by VILLAN3LL3** [comment]
bump

**Comment by albertfc** [comment]
bump

**Comment by nsidhaye** [comment]
I believe this issue is open from 2020...

**Comment by m4rtin195** [comment]
Anybody serious about Kotlin, I recommend switching to Konvert: 
https://github.com/mcarleio/konvert
It's inspired by Mapstruct, and if you don't need some super-complicated mapping scenarios, everything works great.
Mapstruct is ignoring the existence of Kotlin.

**Comment by filiphr** [comment]
This is identical to #2308. However, I am keeping this as I see more people have commented on this one rather on the the other one.

In any case, I've had a better look into supporting Kotlin value classes. However, I do not see how this classes can be invoked from Java.

e.g. if I define

```kotlin
data class Person(var id: PersonId?, var name: String?) {
}

@JvmInline
value class PersonId(val id: String)
```

Then Kotlin will generate a private constructor `Person(String, String)` and we cannot use that from java. If someone can provide me an example where I can instantiate the `Person` in Java than I am more than happy to provide a fix.

The only other way that we could support this is if we would be generating Kotlin code instead of Java code, but I'm not sure how realistic that would be

**Comment by filiphr** [comment]
Thanks for sharing that @audax. I tried setting up an example with `@JvmExposeBoxed`, but if I add it to the data class then I get

```
Kotlin: [Internal Error] org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /Users/filiphr/development/oss/mapstruct/processor/src/test/java/org/mapstruct/ap/test/kotlin/data/jdk17/RecordProperty.kt
The root cause java.lang.IndexOutOfBoundsException was thrown at: java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at org.jetbrains.kotlin.backend.common.BackendException$Companion.report(BackendException.kt:31)
	at org.jetbrains.kotlin.backend.common.BackendException$Companion.report$default(BackendException.kt:15)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(PerformByIrFilePhase.kt:39)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(PerformByIrFilePhase.kt:16)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseEngine.runPhase(PhaseEngine.kt:64)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseEngine.runPhase$default(PhaseEngine.kt:56)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.invokeLowerings(JvmIrCodegenFactory.kt:367)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runLowerings$cli(KotlinToJVMBytecodeCompiler.kt:395)
	at org.jetbrains.kotlin.cli.pipeline.jvm.JvmBackendPipelinePhase.executePhase(JvmBackendPipelinePhase.kt:79)
	at org.jetbrains.kotlin.cli.pipeline.jvm.JvmBackendPipelinePhase.executePhase(JvmBackendPipelinePhase.kt:27)
	at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:68)
	at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:58)
	at org.jetbrains.kotlin.config.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:102)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:22)
	at org.jetbrains.kotlin.config.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:53)
	at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.runPhasedPipeline(AbstractCliPipeline.kt:109)
	at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.execute(AbstractCliPipeline.kt:68)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecutePhased(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecutePhased(K2JVMCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:89)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:359)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1617)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.jetbrains.kotlin.ir.util.IrUtilsKt.usesDefaultArguments(IrUtils.kt:102)
	at org.jetbrains.kotlin.backend.jvm.lower.SyntheticAccessorTransformer.visitFunctionAccess(SyntheticAccessorLowering.kt:142)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:212)
```

so not sure if this is no supported or some bug in the Kotlin compiler

In any case I think for now we can say that we do not support value classes since there is no easy way to work with them from Java.
