### ISSUE TITLE
"FilerException: Attempt to recreate a file for type.." after upgrading to IntelliJ 2021.3.3 the build won't work

### ISSUE THREAD

**Issue by JapuDCret** [mapstruct/mapstruct#2802]
Don't know if this a IntelliJ or MapStruct issue.
Also don't know of a good way how to debug this.

However, after updating I know get the following error message:
```bash
C:\git\my-service\src\main\java\com\example\myservice\domain\DomainMapper.java:25:17
java: Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Attempt to recreate a file for type com.example.myservice.domain.DomainMapperImpl
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:59)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:39)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:29)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:24)
  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:338)
  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:318)
  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)
  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)
  	at org.jetbrains.jps.javac.APIWrappers$ProcessorWrapper.process(APIWrappers.java:157)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:313)
  	at org.mapstruct.ap.MappingProcessor.process(Unknown Source)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1335)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:238)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:518)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:564)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:516)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:359)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:284)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:238)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1507)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1141)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1288)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1106)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.access$1300(IncProjectBuilder.java:71)
  	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer$1.run(IncProjectBuilder.java:1072)
  	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
  	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
  	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
  	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
  	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: javax.annotation.processing.FilerException: Attempt to recreate a file for type com.example.myservice.domain.DomainMapperImpl
  	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:724)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:489)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:426)
  	at org.jetbrains.jps.javac.APIWrappers$FilerWrapper.createSourceFile(APIWrappers.java:246)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:313)
  	at com.sun.proxy.$Proxy30.createSourceFile(Unknown Source)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:56)
  	... 45 more  
```

IntelliJ version output
```
IntelliJ IDEA 2021.3.3 (Ultimate Edition)
Build #IU-213.7172.25, built on March 15, 2022

Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (213.6777.8)
    de.platon42.cajon (1.12)
    com.intellij.guice (213.6461.21)
    org.asciidoctor.intellij.asciidoc (0.37.12)
    PlantUML integration (5.11.1)
    com.intellij.kubernetes (213.6777.8)
    CheckStyle-IDEA (5.62.0)
    zielu.gittoolbox (212.8.8)
    org.intellij.scala (2021.3.20)
    com.haulmont.jpab (2022.1.2-213)

Kotlin: 213-1.5.10-release-949-IJ7172.25
```

All of our Mappers are affected, but here an example:
```java
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public abstract class DomainMapper {

    public static final DomainMapper DOMAIN_MAPPER = Mappers.getMapper(DomainMapper.class);

    public <T extends Serializable> T extractValueObject(AbstractValueObject<T> valueObject) {
        if (valueObject == null) {
            return null;
        }
        return valueObject.getValue();
    }

    @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
    public <T extends Serializable> T extractOptionalValueObject(Optional<? extends AbstractValueObject<T>> optValueObject) {
        if (optValueObject.isEmpty()) {
            return null;
        }
        return extractValueObject(optValueObject.get());
    }
}
```
the actual Mapper that causes this exception seems to be random for each test run.

**Comment by JapuDCret** [comment]
Ok nevermind, this seems to be a problem with our Maven setup and not the IntelliJ update I also did.

Issue seems to be the same as here
https://stackoverflow.com/questions/66978752/how-to-change-mapstruct-generated-sources-location-in-multimodule-maven-project

**Comment by asafacihangir** [comment]
This problem frequently occurs when IntelliJ IDEA and Maven try to compile the project at the same time, leading to conflicts in the creation of the meta-model. Giving Maven complete control over the build process is the answer. Here's how to make it better:

1. Open IntelliJ IDEA.
2. Navigate to: File > `Settings > Build, Execution, Deployment > Build Tools > Maven > Importing`
3. Check the option: `Delegate IDE build/run actions to Maven`
4. Apply the changes and restart IntelliJ IDEA if necessary.

**Comment by andrej-badinka** [comment]
@asafacihangir this helped me, but on my Idea the checkbox is on the `File > Settings > Build, Execution, Deployment > Build Tools > Maven > Runner ` path

Problem now is, that running tests on class in idea now does not generate the green checkboxes per test method, it just redirects to surefire-reports from maven output

**Comment by filiphr** [comment]
>This problem frequently occurs when IntelliJ IDEA and Maven try to compile the project at the same time

How is this happening? Why are you compiling the project with IntelliJ IDEA and Maven in the same time?

I am using the IntelliJ IDEA approach and everything works properly. No need to delegate the build / run actions from IntelliJ to Maven

**Comment by misaya98** [comment]
still happen in idea  version > 202402.4
i don't want to delegate the build to maven. i down grade to the 202402.4

**Comment by andrejb-dev** [comment]
@misaya98 check the Project Settings -> Modules and examine the source folders for any discrepancies

**Comment by Brown-Dan** [comment]
> This problem frequently occurs when IntelliJ IDEA and Maven try to compile the project at the same time, leading to conflicts in the creation of the meta-model. Giving Maven complete control over the build process is the answer. Here's how to make it better:
> 
> 1. Open IntelliJ IDEA.
> 2. Navigate to: File > `Settings > Build, Execution, Deployment > Build Tools > Maven > Importing`
> 3. Check the option: `Delegate IDE build/run actions to Maven`
> 4. Apply the changes and restart IntelliJ IDEA if necessary.

Thanks but the path is > Runner not > Importing

**Comment by ANewCoderMin** [comment]
It helps me too,but i encountered another problem need to toggle maven 'Skip Test mode'

![Image](https://github.com/user-attachments/assets/006f61fe-02af-4d8f-8ce8-7f5dedd0dc45)
