### ISSUE TITLE
Eclipse 2021-12 - Error : Source file already created

### ISSUE THREAD

**Issue by fbrossar25** [mapstruct/mapstruct#2857]
- [x] Is this an issue (and hence not a question)? 

Hello,
this issue is similar to the #2025 as I have the same error in eclipse (stack at the end). Everything is working fine using IntelliJ (I personnaly use it) but the other members of my team uses eclipse.

Steps to reproduce:
 1. delete the generated sources folder one way or another (ex: cleaning project from eclipse, deleting manually, rebuilding after a git pull)
 2. build the eclipse project having Mapstruct as dependency with Project > Build project

It seems to me that eclipse process `@Mapper` files in a certain order and, for a reason or another, return to a file that's already processed, checks if the file to generate is already there, and if it is stops there with an error. 

It is always the same file that trigger the error, but I don't think it comes from the file itself as another file trigger the error if I comment the `@Mapper` annotation.
For exemple ine my case, here's the generated-sources folder:
![image](https://user-images.githubusercontent.com/14792072/170226639-05b0687a-e7d3-44ba-a520-f301b268f88e.png)

And here's the sources folder with every mappers:
![image](https://user-images.githubusercontent.com/14792072/170226811-de8ace9e-70ab-428b-98f5-4a43ff1a5f51.png)

So when the error occurs, the mappers in `queue` in the mapping processors will not be generated.

Some infos:
 - Using Eclipse 2021-12 (4.22.0)
 - [m2e-apt](https://marketplace.eclipse.org/content/m2e-apt) plugin installed
 - [mapstruct plugin](https://marketplace.eclipse.org/content/mapstruct-eclipse-plugin) installed
 - In Preferences > Maven > Annotation Processing, the option `Select Annotation Processing Mode` is set to `Auto configure JDT APT`. (see annotation_processing_setting attached file)
 ![annotation_processing_setting](https://user-images.githubusercontent.com/14792072/170225020-9f5a1ef9-f274-4df8-b0ce-48e36e568c59.PNG)
 - Mapstruct is declared as a dependency into a pom file that is a module of another Maven project (I don't know if it is relevant)
   - partial pom file below
 - I only reproduced the error on mappers that are used on another, but I didn't test on every mappers so maybe it isn't related.
   - partial mapper code below

Have some clues to fix this problem ?
Thanks in advance.

Here's what the mappers declaration looks like
  ```JAVA
  @Mapper(
    componentModel = "spring",
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    nullValueIterableMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public abstract class TheErrorTriggeringMapper {
  // some mapping
}

@Mapper(
    componentModel = "spring",
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    uses = {
      TheErrorTriggeringMapper.class
    })
public abstract class SomeMapper {
  // some mapping
}
   ```

Here's what I have in my pom.xml related to MapStruct:
```XML
<project>
	<parent>
		<groupId>some-group</groupId>
		<artifactId>some-project</artifactId>
	</parent>

    <artifactId>some-project-module</artifactId>

    <properties>
        <mapstruct.version>1.5.0.RC1</mapstruct.version>
        <m2e.apt.activation>jdt_apt</m2e.apt.activation>
    </properties>

    <build>
       <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <!-- in case it is related -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${build-helper-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/java/</source>
                                <source>${project.build.directory}/generated-sources/annotations/</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
       </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
    </dependencies>
</project>
```

Here's the full stack given by eclipse :
```
Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Source file already created: /api-rosa-orm-services/target/generated-sources/annotations/fr/gouv/finances/douane/referentiel/orm/rosa/utils/mapper/relation/eaoe/EaoeSousEaMapperImpl.java
at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:59)
at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:39)
at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:29)
at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:24)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)
at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:113)
at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:950)
at org.eclipse.jdt.int
![annotation_processing_setting](https://user-images.githubusercontent.com/14792072/170223291-224c58db-72c7-41f9-8bb1-5f00cdb30d75.PNG)
ernal.compiler.Compiler.compile(Compiler.java:450)
at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:379)
at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:338)
at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:272)
at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:251)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)  Caused by: javax.annotation.processing.FilerException: Source file already created: /api-rosa-orm-services/target/generated-sources/annotations/fr/gouv/finances/douane/referentiel/orm/rosa/utils/mapper/relation/eaoe/EaoeSousEaMapperImpl.java
at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.createSourceFile(IdeFilerImpl.java:161)
at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:56)  	... 32 more
```

**Comment by Zegveld** [comment]
Do you also use other annotation processors or is mapstruct the only one?

**Comment by fbrossar25** [comment]
Nope, mapstruct is the only one used in the whole project

**Comment by filiphr** [comment]
@fbrossar25 thanks a lot for your detailed issue.

>I only reproduced the error on mappers that are used on another, but I didn't test on every mappers so maybe it isn't related.

This must be related to the Eclipse partial compiling.

I saw that you have

```
<artifactId>build-helper-maven-plugin</artifactId>
```

in your pom.xml. Can you please try to remove that plugin, or at least remove 

```
<source>${project.build.directory}/generated-sources/annotations/</source>
```

That directory is the directory in which the maven-compiler-plugin (and I guess the Eclipse compiler is creating the classes)

By the way, what is created in `<source>${project.build.directory}/generated-sources/java/</source>`?

**Comment by fbrossar25** [comment]
I tried to remove the `<artifactId>build-helper-maven-plugin</artifactId>` plugin and then to remove juste the `<source>${project.build.directory}/generated-sources/annotations/</source>` line, then for each one refreshing the maven projet (alt + F5) and cleaning the project, but it ended up with the same error 😢

> By the way, what is created in <source>${project.build.directory}/generated-sources/java/</source>?

Nothing for the moment, I think it's just some copy/pasted boilerplate code from the begining of the project.
Mapstruct's generated classes are all in `${project.build.directory}/generated-sources/annotations/`, and there's no other generated classes.

**Comment by Zegveld** [comment]
it is important that `${project.build.directory}/generated-sources/annotations/` and `${project.build.directory}/generated-sources/` are not yet present as a source when mapstruct starts doing it's code generation. If it is then you will get that exception. Mapstruct itself should add `${project.build.directory}/generated-sources/annotations/` to the source list.

**Comment by fbrossar25** [comment]
@Zegveld  I removed the `<artifactId>build-helper-maven-plugin</artifactId>` part from my pom.xml, and just for testing I also removed the `maven-compiler-plugin` part too (which remove mapstruct-processor from being called), and after that the `target/generated-sources/annotations` folder is still created at build, but as expected no sources are generated, so this folder is empty.
Isn't maven creating this folder itself by default ?

**Comment by fbrossar25** [comment]
Nevermind, it's the m2e-apt plugin that's creating the folder, I unchecked this option and the folder isn't created anymore:
![image](https://user-images.githubusercontent.com/14792072/171203690-c643903a-7628-481a-b50f-89901d4d6942.png)

**Comment by filiphr** [comment]
>Isn't maven itself creating this folder by default ?

Yes the maven-compiler is the one that is creating the `${project.build.directory}/generated-sources/annotations/` and also the m2e-apt plugin is creating it, since it configures itself from the maven-compiler-plugin configuration.

If this worked with an older Eclipse version, then there must be something wrong on the Eclipse side. Usually the IDE is responsible for cleaning things up before recompiling the new classes.

**Comment by shixiuhai** [comment]
i have same issue https://github.com/redhat-developer/vscode-java/issues/3668
