### ISSUE TITLE
`Optional` wrapping pattern broken in 1.5.2.Final

### ISSUE THREAD

**Issue by facboy** [mapstruct/mapstruct#2925]
I have an issue similar to #2673 in 1.5.2.Final.  Project to reproduce: https://github.com/facboy/mapstruct-bug

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/xyz/git/mapstruct-bug/src/main/java/org/facboy/mapstruct/OptionalBeanMapper.java:[6,16] error: Internal error in the mapping processor: java.lang.IllegalArgumentException: long     at jdk.compiler/com.sun.tools.javac.model.JavacTypes.getDeclaredType0(JavacTypes.java:272)     at jdk.compiler/com.sun.tools.javac.model.JavacTypes.getDeclaredType(JavacTypes.java:241)      at org.mapstruct.ap.internal.util.AbstractTypeUtilsDecorator.getDeclaredType(AbstractTypeUtilsDecorator.java:119)     at org.mapstruct.ap.internal.model.source.MethodMatcher$GenericAnalyser.resolve(MethodMatcher.java:384)          at org.mapstruct.ap.internal.model.source.MethodMatcher$GenericAnalyser.lineUp(MethodMatcher.java:173)         at org.mapstruct.ap.internal.model.source.MethodMatcher$GenericAnalyser.access$000(MethodMatcher.java:109)     at org.mapstruct.ap.internal.model.source.MethodMatcher.matches(MethodMatcher.java:70)         at org.mapstruct.ap.internal.model.source.SourceMethod.matches(SourceMethod.java:514)          at org.mapstruct.ap.internal.model.source.selector.TypeSelector.lambda$getMatchingParameterBinding$0(TypeSelector.java:164)    at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)          at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)         at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingParameterBinding(TypeSelector.java:163)     at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingMethods(TypeSelector.java:77)       at org.mapstruct.ap.internal.model.source.selector.MethodSelectors.getMatchingMethods(MethodSelectors.java:67)        at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getBestMatch(MappingResolverImpl.java:485)         at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:230)         at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:169)          at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:145)          at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:256)      at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1412)        at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1376)        at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:294)          at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:418)     at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:181)     at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:135)       at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:82)        at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)        at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)        at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)          at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)          at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)     at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)   at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)    at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)   at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)  at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)   at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
[INFO] 1 error
```

**Comment by filiphr** [comment]
Thanks a lot for the reproducable repo @facboy. We've managed to use it to locate the problem and have a PR #2927 for fixing this

**Comment by facboy** [comment]
👍
