### ISSUE TITLE
NullPointerException for class with unknown annotation

### ISSUE THREAD

**Issue by chschu** [mapstruct/mapstruct#297]
If a MapStruct-enabled maven module contains at least one valid mapper and a class that has an unknown annotation on the type level, the annotation processor fails. The actual compilation problem is shadowed by the following NullPointerException:

```
java.lang.NullPointerException
    at org.mapstruct.ap.util.MapperConfig.<init>(MapperConfig.java:64)
    at org.mapstruct.ap.util.MapperConfig.getInstanceOn(MapperConfig.java:55)
    at org.mapstruct.ap.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetrievalProcessor.java:99)
    at org.mapstruct.ap.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:71)
    at org.mapstruct.ap.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:60)
    at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:181)
    at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:161)
    at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:142)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
```

To reproduce, add the following two classes to a MapStruct-enabled maven module and run `mvn clean compile -e`:

``` java
@UnknownAnnotation
public class CannotBeCompiled {
}
```

``` java
import org.mapstruct.Mapper;

@Mapper
public interface DummyMapper {
}
```

**Comment by eapereira** [comment]
I just getting this error now()!

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-07-04T14:59:27-0300",
    comments = "version: 1.2.0.Final, compiler: javac, environment: Java 1.8.0_131 (Oracle Corporation)"
)
public class ContratoMapperImpl extends ContratoMapper {

    private final UserMapper userMapper = Mappers.getMapper( UserMapper.class );
    private final LancamentoMapper lancamentoMapper = Mappers.getMapper( LancamentoMapper.class );

    @Override
    public void copyProperties(Contrato source, ContratoUi target) {
        if ( source == null ) {
            return;
        }

```
```
Caused by: java.lang.NullPointerException
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.mapper.ui.UserMapperImpl.copyProperties(UserMapperImpl.java:944)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.mapper.ui.UserMapperImpl.copyProperties(UserMapperImpl.java:36)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.mapper.ui.ContratoMapperImpl.copyProperties(ContratoMapperImpl.java:30)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.mapper.ui.ContratoMapperImpl.copyProperties(ContratoMapperImpl.java:11)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.ui.ContratoUi.copyProperties(ContratoUi.java:25)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.AbstractDomain.<init>(AbstractDomain.java:48)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.Contrato.<init>(Contrato.java:34)
	at br.com.spread.qualicorp.wso2.coparticipacao.domain.ui.ContratoUi.<init>(ContratoUi.java:19)
	at br.com.spread.qualicorp.wso2.coparticipacao.service.impl.ContratoServiceImpl.entityToUi(ContratoServiceImpl.java:49)
	at br.com.spread.qualicorp.wso2.coparticipacao.service.impl.ContratoServiceImpl.findByCdContrato(ContratoServiceImpl.java:37)
	... 35 more
2018-07-04 15:00:04.085 DEBUG Wolfenstein --- [           main] c.DefaultCacheAwareContextLoaderDelegate : Retrieved ApplicationContext from cache with key [[WebMergedContextConfiguration@389c4eb1 testClass = CoParticipacaoServiceTest, locations = '{}', classes = '{class br.com.spread.qualicorp.wso2.coparticipacao.test.config.CoParticipacaoWebServiceConfigurationTest}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@49c7b90e, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@3e84448c, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@5562c41e, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1a18644], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2018-07-04
```

Java JDK 1.8.0-131

**Comment by chris922** [comment]
@eapereira looks like you don't have the same issue like this one here. Maybe it's better that you create a new issue for this and please include at least the complete `copyProperties` method and highlight the line `944` where the NPE occurs.

**Comment by eapereira** [comment]
The exception raised from the annotation @Generated, exactly:
ContratoMapperImpl.java:11

```
package br.com.spread.qualicorp.wso2.coparticipacao.domain.mapper.ui;

import br.com.spread.qualicorp.wso2.coparticipacao.domain.Contrato;
import br.com.spread.qualicorp.wso2.coparticipacao.domain.Lancamento;
import br.com.spread.qualicorp.wso2.coparticipacao.domain.ui.ContratoUi;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-07-04T18:57:16-0300",
    comments = "version: 1.2.0.Final, compiler: javac, environment: Java 1.8.0_131 (Oracle Corporation)"
)
public class ContratoMapperImpl extends ContratoMapper {

    @Override
    public void copyProperties(Contrato source, ContratoUi target) {
        if ( source == null ) {
            return;
        }

        target.setId( source.getId() );
        target.setAltered( source.getAltered() );
        target.setCreated( source.getCreated() );
        target.setUserCreated( source.getUserCreated() );
        target.setUserAltered( source.getUserAltered() );
        target.setCdContrato( source.getCdContrato() );
        target.setNameContrato( source.getNameContrato() );
        target.setEmpresa( source.getEmpresa() );
        if ( target.getLancamentos() != null ) {
            List<Lancamento> list = source.getLancamentos();
            if ( list != null ) {
                target.getLancamentos().clear();
                target.getLancamentos().addAll( list );
            }
            else {
                target.setLancamentos( null );
            }
        }
        else {
            List<Lancamento> list = source.getLancamentos();
            if ( list != null ) {
                target.setLancamentos( new ArrayList<Lancamento>( list ) );
            }
        }
        target.setArquivoInput( source.getArquivoInput() );
    }

    @Override
    public void copyProperties(List<Contrato> sources, List<Contrato> targets) {
        if ( sources == null ) {
            return;
        }

        targets.clear();
        for ( Contrato contrato : sources ) {
            targets.add( copyProperties( contrato ) );
        }
    }

    @Override
    public ContratoUi copyProperties(Contrato source) {
        if ( source == null ) {
            return null;
        }

        ContratoUi contratoUi = getTarget();

        contratoUi.setId( source.getId() );
        contratoUi.setAltered( source.getAltered() );
        contratoUi.setCreated( source.getCreated() );
        contratoUi.setUserCreated( source.getUserCreated() );
        contratoUi.setUserAltered( source.getUserAltered() );
        contratoUi.setCdContrato( source.getCdContrato() );
        contratoUi.setNameContrato( source.getNameContrato() );
        contratoUi.setEmpresa( source.getEmpresa() );
        List<Lancamento> list = source.getLancamentos();
        if ( list != null ) {
            contratoUi.setLancamentos( new ArrayList<Lancamento>( list ) );
        }
        else {
            contratoUi.setLancamentos( null );
        }
        contratoUi.setArquivoInput( source.getArquivoInput() );

        return contratoUi;
    }
}

```

I will try to make more tests to identify if it still happening.

**Comment by chris922** [comment]
`userUi.setId( source.getId() );`

`userUi` could not be null, `source` could not be null. NPE during auto unboxing? So could it be that `getId()` returns `null` but `setId()` requires the primitive `int` and not `Integer`

Line11 is just one part of the stacktrace. The most interesting one is the line 944 where the NPE occurred.

**Comment by eapereira** [comment]
This error had something related to circular mapper dependence, it moved me to use mappers managed by spring.
