### ISSUE TITLE
This plugin is not a production of JetBrains. Please report the problem to MapStruct.

### ISSUE THREAD

**Issue by MajkPacholski** [mapstruct/mapstruct#3328]
### Expected behavior

working on  intelij

### Actual behavior

problem has start after install plugin 

### Steps to reproduce the problem

IDE Internal Errors
→
1 of 3 Exception in plugin MapStruct Support (1.6.1). Disable plugin...
This plugin is not a production of JetBrains. Please report the problem to MapStruct.
X
Moments ago, occurred once

### MapStruct Version

1.6.1

**Comment by filiphr** [comment]
@MajkPacholski can you please share the version of IntelliJ where you tried this and also share more of the errors which are in the report in IntelliJ

**Comment by MajkPacholski** [comment]
om.intellij.diagnostic.PluginException: Cannot create class org.mapstruct.intellij.inspection.WrongUsageOfMappersFactoryInspection (classloader=PluginClassLoader(plugin=PluginDescriptor(name=MapStruct Support, id=org.mapstruct.intellij, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\mapstruct-intellij-1.6.1.jar, version=1.6.1, package=null, isBundled=false), packagePrefix=null, instanceId=333, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:28)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:224)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:84)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getGroupDisplayName(InspectionToolWrapper.java:152)
	at com.intellij.ide.ui.ToolOptionDescription.<init>(ToolOptionDescription.java:20)
	at com.intellij.ide.ui.InspectionsTopHitProvider.getOptions(InspectionsTopHitProvider.java:31)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:60)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:47)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions$lambda$0(TopHitCache.kt:47)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.kt:47)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.execute(OptionsTopHitProvider.kt:155)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity$execute$1.invokeSuspend(OptionsTopHitProvider.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NoClassDefFoundError: org/mapstruct/Mapper
	at org.mapstruct.intellij.util.MapstructUtil.<clinit>(MapstructUtil.java:78)
	at org.mapstruct.intellij.inspection.WrongUsageOfMappersFactoryInspection.<clinit>(WrongUsageOfMappersFactoryInspection.java:42)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:993)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.mapstruct.Mapper PluginClassLoader(plugin=PluginDescriptor(name=MapStruct Support, id=org.mapstruct.intellij, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\mapstruct-intellij-1.6.1.jar, version=1.6.1, package=null, isBundled=false), packagePrefix=null, instanceId=333, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 more

**Comment by MajkPacholski** [comment]
IntelliJ IDEA 2023.1.4 (Ultimate Edition)
Build #IU-231.9225.16, built on July 12, 2023
Licensed to Majk Niga
Subscription is active until August 11, 2023.
Evaluation purpose only.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.jax.ws (231.8109.90)
    org.jetbrains.kotlin (231-1.9.0-release-358-IJ8770.65)
    dev.nx.console (1.10.0)
    org.mapstruct.intellij (1.6.1)
    com.intellij.spring.websocket (231.8770.17)

Kotlin: 231-1.9.0-release-358-IJ8770.65

**Comment by filiphr** [comment]
How did you install the plugin @MajkPacholski? I've been using the plugin on 2023.1 and 2023.2 without any issues
