### ISSUE TITLE
MapStruct 1.6.3 passes builder as @MappingTarget Object target to the context#storeMappedInstance

### ISSUE THREAD

**Issue by BbIKTOP** [mapstruct/mapstruct#3778]
### Expected behavior

I have two classes - entity and dto. Both are annotated with lombok's ```@Builder```
As they have circular references, I use CycleAvoidingMappingContext copypasted from the example. 
I expect it to be working.

### Actual behavior

And here's the generated code, I suppose it's not really ok:

```
    @Override
    public DomainDto toDto(Domain domain, CycleAvoidingMappingContext context) {
        DomainDto target = context.getMappedInstance( domain, DomainDto.class );
        if ( target != null ) {
            return target;
        }

        if ( domain == null ) {
            return null;
        }

        DomainDto.DomainDtoBuilder domainDto = DomainDto.builder();

// Here
       context.storeMappedInstance( domain, domainDto );

        domainDto.id( domain.getId() );
        domainDto.name( domain.getName() );
        domainDto.description( domain.getDescription() );
        domainDto.tableMappings( tableMappingSetToTableMappingDtoSet( domain.getTableMappings(), context ) );
        domainDto.tenantDomains( tenantDomainSetToTenantDomainDtoSet( domain.getTenantDomains(), context ) );

        return domainDto.build();
    }


```

As you see, it uses builder instead of actual class. Dunno what was the idea, but it surely leads to the nice ClassCastException 
```
class com.somecompany.dto.TableTenantStateDto$TableTenantStateDtoBuilder cannot be cast to class com.somecompany.dto.TableTenantStateDto (com.somecompany.dto.TableTenantStateDto$TableTenantStateDtoBuilder and com.somecompany.dto.TableTenantStateDto are in unnamed module of loader 'app')
java.lang.ClassCastException: class com.somecompany.dto.TableTenantStateDto$TableTenantStateDtoBuilder cannot be cast to class com.somecompany.dto.TableTenantStateDto (com.somecompany.dto.TableTenantStateDto$TableTenantStateDtoBuilder and com.somecompany.dto.TableTenantStateDto are in unnamed module of loader 'app')
	at com.somecompany.config.mapper.DtoMapperImpl.toDto(DtoMapperImpl.java:398)
	at com.somecompany.config.mapper.DtoMapperImpl.tableTenantStateSetToTableTenantStateDtoSet(DtoMapperImpl.java:672)
	at com.somecompany.config.mapper.DtoMapperImpl.toDto(DtoMapperImpl.java:253)
	at com.somecompany.config.mapper.DtoMapperImpl.toDto(DtoMapperImpl.java:415)
	at com.somecompany.config.mapper.DtoMapperImpl.tableTenantStateSetToTableTenantStateDtoSet(DtoMapperImpl.java:672)
	at com.somecompany.config.mapper.DtoMapperImpl.toDto(DtoMapperImpl.java:361)
	at com.somecompany.config.mapper.DtoMapperImpl.tableMappingSetToTableMappingDtoSet(DtoMapperImpl.java:592)
	at com.somecompany.config.mapper.DtoMapperImpl.toDto(DtoMapperImpl.java:160)
	at com.somecompany.config.mapper.DtoMapperTest.domainDtoTest(DtoMapperTest.java:134)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

### Steps to reproduce the problem

```
@Mapper(componentModel = "spring",
        uses = {
                DomainRepository.class,
        },
        imports = {LinkedHashSet.class, HashSet.class},
        injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public abstract class DtoMapper {
    @Autowired
    private BookmarkRepository bookmarkRepository;
    @Autowired
    private ColumnMappingRepository columnMappingRepository;
    @Autowired
    private DomainRepository domainRepository;
    @Autowired
    private FbVersionRepository fbVersionRepository;
    @Autowired
    private ReplicationStatusRepository replicationStatusRepository;
    @Autowired
    private RowsMetadatumRepository rowsMetadatumRepository;
    @Autowired
    private TableMappingRepository tableMappingRepository;
    @Autowired
    private TableTenantStateRepository tableTenantStateRepository;
    @Autowired
    private TenantDomainRepository tenantDomainRepository;
    @Autowired
    private TenantRepository tenantRepository;

/*
    public DtoMapper(BookmarkRepository bookmarkRepository,
                     ColumnMappingRepository columnMappingRepository,
                     DomainRepository domainRepository,
                     FbVersionRepository fbVersionRepository,
                     ReplicationStatusRepository replicationStatusRepository,
                     RowsMetadatumRepository rowsMetadatumRepository,
                     TableMappingRepository tableMappingRepository,
                     TableTenantStateRepository tableTenantStateRepository,
                     TenantDomainRepository tenantDomainRepository,
                     TenantRepository tenantRepository) {
        this.bookmarkRepository = bookmarkRepository;
        this.columnMappingRepository = columnMappingRepository;
        this.domainRepository = domainRepository;
        this.fbVersionRepository = fbVersionRepository;
        this.replicationStatusRepository = replicationStatusRepository;
        this.rowsMetadatumRepository = rowsMetadatumRepository;
        this.tableMappingRepository = tableMappingRepository;
        this.tableTenantStateRepository = tableTenantStateRepository;
        this.tenantDomainRepository = tenantDomainRepository;
        this.tenantRepository = tenantRepository;
    }
*/
...
    // Domain

    public abstract DomainDto toDto(Domain domain, @Context CycleAvoidingMappingContext context);

    public abstract Domain toEntity(DomainDto domainDto, @Context CycleAvoidingMappingContext context);
...
```
And test:
```
@Test
    @Order(3)
    @Transactional
    public void domainDtoTest() {
        DomainDto domainDto = mapper.toDto(domain, new CycleAvoidingMappingContext());
        assertThat(domainDto).isNotNull();
```

### MapStruct Version

MapStruct 1.6.3

**Comment by filiphr** [comment]
@BbIKTOP, sorry but I do not see the problem. The `CycleAvoidingMappingContext` is an example for how you can map cycles. It is entirely up to you to adjust it to your own needs.

I would suggest that you provide an entire reproducible example that we can look into.

**Comment by BbIKTOP** [comment]
Sorry, after spending a few hours trying to make it work I decided to proceed without mapstruct as it took more time than implementing my simple mappers by myself.
But I suppose that as a maintainer/developer you could be interested in bug fixing, that's why gave you a feedback. I surely understand how this cycleavoidingcomtext map works, it's not a quantum physics or even rocket science. See, as there are two beans "DomainDto" and "Domain" , both annotated with Lombock's "Builder", MapStruct definitely should not put **builder** to the context and should not return it as a mapping result, isn't it?
Like, in the generated code I've shared above:

```
        DomainDto.DomainDtoBuilder domainDto = DomainDto.builder();
       context.storeMappedInstance( domain, domainDto );
```

Maybe the first line should be builder().build() or something instead of storing **builder** in the context.
Sorry, I am a bit busy working, just wanted to help but have no time to elaborate further as I am not going to use MapStruct anymore. If you're interested in bug fixing, you could definitely make an mve with two pojo bean classes annotated with Lombok's "@Builder", "@Data" and allargs/noargs structors and check.

Thank you!

**Comment by TMRGZ** [comment]
Hi, I think I reported this issue a time ago here https://github.com/mapstruct/mapstruct/issues/3722 where I provided an example repository.

As a workaround, in the CycleAvoidingMappingContext I called the build method through reflection, but I think it does not work as well as MapStruct 1.5.5, would be great to have a config to restore the old functionality

```java
public class CycleAvoidingMappingContext {

  private static final Map<Object, Object> ALREADY_MAPPED = new IdentityHashMap<>();

  @BeforeMapping
  public <T> T getMappedInstance(Object source, @TargetType Class<T> targetType) {
    var stored = ALREADY_MAPPED.get(source);

    if (Objects.isNull(stored) || targetType.isAssignableFrom(stored.getClass())) {
      return targetType.cast(stored);
    }

    var built = processBuilder(stored);
    storeMappedInstance(source, built);
    return getMappedInstance(source, targetType);
  }

  @BeforeMapping
  public void storeMappedInstance(Object source, @MappingTarget Object target) {
    ALREADY_MAPPED.put(source, target);
  }

  protected Object processBuilder(Object storedBuilder) {
    try {
      return MethodUtils.invokeExactMethod(storedBuilder, "build");
    } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
      throw new RuntimeException(e);
    }
  }
}
```

**Comment by BbIKTOP** [comment]
I've been told by colleagues that the main advantage of mapStruct over a modelmapper is that mapstruct does not use reflection. This workaround could cost a fortune in the meaning of resources.
Anyways, thank you for your help!

**Comment by Zegveld** [comment]
The `CycleAvoidingMappingContext` doesn't work nicely with `Builder`s because the item is not build yet the moment you want to use it again. You also can't build it at that point, because it will result in a different object then you want.

Look at the steps below, to see the problem more plain:
1. Start mapping object A using builder.
1.1. Store builder in context.
1.2. Check context, B not present therefor start mapping child object B using builder.
1.2.1. Store builder in context.
1.2.2. Check context, A is present as builder, if build it is an empty object A, because the first level of building is not completed.
1.3 The remaining mappings are not present in B.A because building A results in a different object.

My suggestion would be to tell mapstruct to not use the builders for mappings, that way you get the following:
1. Start mapping object A.
1.1. Store initially created object A in context.
1.2. Check context, B not present therefor start mapping child object B.
1.2.1. Store initially created object B in context.
1.2.2. Check context, A is present, store this reference to A in object B.
1.3 The remaining mappings are present in B.A

**Comment by TMRGZ** [comment]
My problem would be in case I use records, I need the builder to create the object while is being cached in the context and disabling it leads to an endless loop

**Comment by Zegveld** [comment]
> My problem would be in case I use records, I need the builder to create the object while is being cached in the context and disabling it leads to an endless loop

That is basically the main problem with immutability/records.

If you have a cycle at any point in your model structure, this means that you cannot create either object.

For example:
```java
record Car(Owner owner){}
record Owner(Car car){}
```

If I create an `Owner` without a `Car`, and then a `Car` with that `Owner`. The `Owner` still doesn't know about the `Car`.
As soon as I create a new `Owner` that does have that `Car` assigned to it, the `Car` itself thinks it is owned by someone else.
With immutable models it is impossible to wire everything correctly so that `Owner` refers to `Car` and vise-versa.

Object flow:
1. `Owner A = new Owner(null);`
2. `Car B = new Car(A)`
3. `Owner C = new Owner(B)`
now `C` is not the same as `C.getCar().getOwner()`, because `C.getCar()` = `B` and `B.getOwner()` = `A`.

As soon as I make either `Owner` or `Car` not immutable anymore, it becomes possible to create an `Owner` that knows the `Car` and at the same time having that `Car` know the `Owner`. 

If you have the following records for example:
```java
record Teacher(List<Students> students){} // the list of students does not have to be immutable here.
record Student(Teacher teacher){}
```

you could do the following:
```java
@Mapper
interface MyMapper {
  default Teacher MapTeacher( TeacherDto dto, @Context CycleAvoidingMappingContext context ) {
    List<Students> students = new ArrayList<>();
    Teacher teacher = new Teacher(students);
    context.storeMappedInstance( dto, teacher ); // store the teacher so it will not be re-created while handling the students.
    for( StudentDto studentDto : dto.getStudents() ){
      students.add( mapStudent( studentDto, context ) );
    }
    return teacher; // the list of students is not immutable.
  }
  
  Student mapStudent( StudentDto dto, @Context CycleAvoidingMappingContext context ); // mapstruct will use the context to not create the teacher again.
}
```

Instead of changing MapStruct for this I would sooner suggest a redesign the above record model to have Teacher as a class with functionality nearing immutability instead:
```java
class Teacher {
  private final List<Student> students = new ArrayList<>();
  
  void addStudent(Student student) { // only add functionality for mutability
    this.students.add(student);
  }

  List<Student> getStudents() {
    return Collections.unmodifiableList(students);
  }
}
record Student(Teacher teacher);
```

I'm of the opinion that this is not a bug or a problem that should be solved in mapstruct, marking this for closing if no response.
wdyt @filiphr?

**Comment by filiphr** [comment]
I agree with you about this @Zegveld. Cycles and builders don't really go nicely together, and you did provide some good additional explanations in https://github.com/mapstruct/mapstruct/issues/3722#issuecomment-2518705550
