### ISSUE TITLE
NPE when defining mapping to primitive array

### ISSUE THREAD

**Issue by tfeuerba** [mapstruct/mapstruct#3786]
### Expected behavior

Obviously this is not supported, but a better error message would be great

### Actual behavior

```
Internal error in the mapping processor: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.TypeElement.getEnclosedElements()" because "this.typeElement" is null
at org.mapstruct.ap.internal.model.common.Type.hasAccessibleConstructor(Type.java:1341)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.canReturnTypeBeConstructed(BeanMappingMethod.java:771)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.doesNotAllowAbstractReturnTypeAndCanBeConstructed(BeanMappingMethod.java:485)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:211)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:427)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:188)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:142)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:85)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:400)
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:380)
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:329)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:213)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
```

### Steps to reproduce the problem

Java 17

Define this Mapper interface:

```
@Mapper
public interface TestMapper {
    byte[] map(String something);
}
```

### MapStruct Version

1.6.3

**Comment by Zegveld** [comment]
I'm looking in to this, because crashes are indeed not nice.

In case of `byte map(String something)` we already give a message `Can't generate mapping method with primitive return type.`
I guess we can do the same for `byte[] map(String something)` and other primitive types like it.
I think the message would be something like `Can't generate mapping method with primitive array return type.`

Working on a PR to implement this check.

**Comment by Zegveld** [comment]
Looking into it further I think the message would probably more like, `Cannot create mapping from String to byte[]`.
We already have use-cases in our tests that support primitive array mappings, so this support should remain.

**Comment by agitrubard** [comment]
@Zegveld you need to write your own mapper for mapping bytes like this;

In my case, I was need to convert `ByteArray` to `byte[]` and `byte[]` to `ByteArray`. I was created my own `ByteArrayMapper`.

```java
@Mapper
public interface ByteArrayMapper {

    default ByteArray byteArrayFromByte(byte[] value) {

        if (value == null) {
            return null;
        }

        return new ByteArray(value);
    }

    @SuppressWarnings("java:S1168")
    default byte[] byteFromByteArray(ByteArray value) {

        if (value == null) {
            return null;
        }

        return value.getBytes();
    }

}
```

And I used this converter I wrote as follows;
```java
@Mapper(uses = ByteArrayMapper.class)
public interface MyMapper extends BaseMapper<MySourceClass, MyTargetClass> {
.
.
.
```

---

If you want to look, I leave the `BaseMapper` class here;

```java
public interface BaseMapper<S, T> {

    T map(S source);

    List<T> map(Collection<S> source);

}
```
The purpose of this class is not to have to redefine methods in every mapper I create.

**Comment by tfeuerba** [comment]
@agitrubard Thanks, I am aware that there is no out-of-the-box mapping for byte[] to String. This issue here is about turning the NPE into a clear error message, and Zegveld provided a fix for that. This helps to distinguish a user error from an actual bug.
