### ISSUE TITLE
Occasional NullPointerException when flushing output streams

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#504]
Every now and then, in our multithreaded build, we get:

```
Caused by: java.lang.NullPointerException
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:119)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.FilterWriter.write(FilterWriter.java:78)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter$State$1.flush(IndentationCorrectingWriter.java:146)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter$State$1.onExit(IndentationCorrectingWriter.java:134)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter.close(IndentationCorrectingWriter.java:82)
	at java.io.BufferedWriter.close(BufferedWriter.java:266)
	at org.mapstruct.ap.writer.ModelWriter.writeModel(ModelWriter.java:71)
	at org.mapstruct.ap.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:68)
	at org.mapstruct.ap.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:50)
	at org.mapstruct.ap.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:41)
	at org.mapstruct.ap.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:36)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:193)
	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:173)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:154)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

Rerunning the build usually helps.

For StreamEncoder, I only have the disassembled bytecode:
```
  public void write(char[], int, int) throws java.io.IOException;
    Code:
       0: aload_0
       1: getfield      #222                // Field lock:Ljava/lang/Object;
       4: dup
       5: astore        4
       7: monitorenter
       8: aload_0
       9: invokespecial #269                // Method ensureOpen:()V
      12: iload_2                                 // <---- this seems to be line 119
      13: iflt          40
      16: iload_2
      17: aload_1
      18: arraylength
      19: if_icmpgt     40
      22: iload_3
      23: iflt          40
      26: iload_2
      27: iload_3
      28: iadd
      29: aload_1
      30: arraylength
      31: if_icmpgt     40
      34: iload_2
      35: iload_3
      36: iadd
      37: ifge          48
      40: new           #111                // class java/lang/IndexOutOfBoundsException
      43: dup
      44: invokespecial #238                // Method java/lang/IndexOutOfBoundsException."<init>":()V
      47: athrow
      48: iload_3
      49: ifne          56
      52: aload         4
      54: monitorexit
      55: return
      56: aload_0
      57: aload_1
      58: iload_2
      59: iload_3
      60: invokevirtual #275                // Method implWrite:([CII)V
      63: aload         4
      65: monitorexit
      66: goto          77
      69: astore        5
      71: aload         4
      73: monitorexit
      74: aload         5
      76: athrow
      77: return
    Exception table:
       from    to  target type
           8    55    69   any
          56    66    69   any
          69    74    69   any
    LineNumberTable:
      line 117: 0
      line 118: 8
      line 119: 12
      line 121: 40
      line 122: 48
      line 123: 52
      line 125: 56
      line 126: 63
      line 127: 77
```

@gunnarmorling: any idea? Could it be that there is nothing left to flush and the computed length is 0?

**Comment by agudian** [comment]
Think I found it: it can happen that in ```IndentationCorrectingWriter.State.IN_TEXT.{...}.flush(StateContext)```, the context still only has an unchanged ````characters``` array (i.e. ```null```). That would lead to an NPE at the exact line in StreamEncoder.
