### ISSUE TITLE
negative array size exception

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#515]
Caused by: org.codehaus.plexus.compiler.CompilerException: java.lang.NegativeArraySizeException
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:172)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:823)
	... 22 more
Caused by: java.lang.RuntimeException: java.lang.NegativeArraySizeException
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
	... 24 more
Caused by: java.lang.NegativeArraySizeException
	at org.mapstruct.ap.writer.IndentationCorrectingWriter.getIndentation(IndentationCorrectingWriter.java:91)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter.access$200(IndentationCorrectingWriter.java:37)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter$State$1.doOnEntry(IndentationCorrectingWriter.java:122)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter$State.onEntry(IndentationCorrectingWriter.java:235)
	at org.mapstruct.ap.writer.IndentationCorrectingWriter.write(IndentationCorrectingWriter.java:65)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)

**Comment by sjaakd** [comment]
Seem to occur when expression is not correct:

expression = "java(mapToCodeType( in.getAuthority), CODETYPE_AUTHORITY ))")

**Comment by sjaakd** [comment]
Solution created and merged.
