### ISSUE TITLE
Nullpointer at SpecificCompilerWorkarounds.java:90

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#526]
Situation: 

Mapping method:
`    protected abstract DossierDto mapToDtoInt( BlkLocatie in ) throws ConverterException;`

Source object:
```java
public interface BlkLocatie<T1 extends BlkGeoobjectType, T2 extends BlkAdresType> {

    T1 getGeoobject();
    void setGeoobject( T1 value );
    T2 getAdres();
    void setAdres( T2 value );
}
```

TargetObject: java```DossierDto extends SoilManagementDossierDto```
```java
public class SoilManagementDossierDto implements Serializable {
    private static final long serialVersionUID = 1L;

    private SoilLocationDto soilLocation;
	...
```
Mapping method available:
 ```java
protected abstract SoilLocationDto map( BlkGeoobjectType in ) throws ConverterException;
``` 

Effect:

`
Caused by: java.lang.NullPointerException
	at org.mapstruct.ap.util.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:90)
	at org.mapstruct.ap.util.Executables.getAllEnclosedExecutableElements(Executables.java:189)
	at org.mapstruct.ap.model.common.Type.getAllExecutables(Type.java:395)
	at org.mapstruct.ap.model.common.Type.getPropertyReadAccessors(Type.java:324)
	at org.mapstruct.ap.model.source.SourceReference$BuilderFromMapping.getSourceEntries(SourceReference.java:176)
	at org.mapstruct.ap.model.source.SourceReference$BuilderFromMapping.build(SourceReference.java:139)
	at org.mapstruct.ap.model.source.Mapping.init(Mapping.java:202)
	at org.mapstruct.ap.model.source.SourceMethod$Builder.build(SourceMethod.java:186)
	at org.mapstruct.ap.processor.MethodRetrievalProcessor.getMethodRequiringImplementation(MethodRetrievalProcessor.java:248)
	at org.mapstruct.ap.processor.MethodRetrievalProcessor.getMethod(MethodRetrievalProcessor.java:191)
	at org.mapstruct.ap.processor.MethodRetrievalProcessor.retrieveMethods(MethodRetrievalProcessor.java:148)
	at org.mapstruct.ap.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:93)
	at org.mapstruct.ap.processor.MethodRetrievalProcessor.process(MethodRetrievalProcessor.java:68)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:193)
	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:173)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:154)
`

**Comment by sjaakd** [comment]
I'm having troubles reproducing this one. I made a test case but it does not reproduce. So I suspect my sources were somehow not up to date (e.g. the interface library BlkLocatie is out of sync with the implementation library).  So I'll close this one.
