### ISSUE TITLE
Integration test SimpleTest#orcale_java_6 fails

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#551]
```java
java.lang.AssertionError: isSubtype 15
	at com.sun.tools.javac.code.Types$5.visitType(Types.java:355)
	at com.sun.tools.javac.code.Types$5.visitType(Types.java:336)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visitWildcardType(Types.java:3205)
	at com.sun.tools.javac.code.Type$WildcardType.accept(Type.java:416)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:3203)
	at com.sun.tools.javac.code.Types.isSubtype(Types.java:332)
	at com.sun.tools.javac.code.Types.isSubtype(Types.java:316)
	at com.sun.tools.javac.code.Types.isSubtypeUnchecked(Types.java:287)
	at com.sun.tools.javac.code.Types.isConvertible(Types.java:256)
	at com.sun.tools.javac.code.Types.isAssignable(Types.java:1484)
	at com.sun.tools.javac.code.Types.isAssignable(Types.java:1445)
	at com.sun.tools.javac.model.JavacTypes.isAssignable(JavacTypes.java:86)
	at org.mapstruct.ap.processor.creation.MappingResolverImpl$ResolvingAttempt.collectionTypeHasCompatibleConstructor(MappingResolverImpl.java:556)
	at org.mapstruct.ap.processor.creation.MappingResolverImpl$ResolvingAttempt.isPropertyMappable(MappingResolverImpl.java:510)
	at org.mapstruct.ap.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:195)
	at org.mapstruct.ap.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:146)
	at org.mapstruct.ap.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:114)
	at org.mapstruct.ap.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:181)
	at org.mapstruct.ap.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:419)
	at org.mapstruct.ap.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:127)
	at org.mapstruct.ap.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:349)
	at org.mapstruct.ap.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)
	at org.mapstruct.ap.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114)
	at org.mapstruct.ap.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:208)
	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:188)
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:157)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:556)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:701)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:987)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
	at com.sun.tools.javac.main.Main.compile(Main.java:353)
	at com.sun.tools.javac.main.Main.compile(Main.java:279)
	at com.sun.tools.javac.main.Main.compile(Main.java:270)
	at com.sun.tools.javac.Main.compile(Main.java:69)
	at com.sun.tools.javac.Main.main(Main.java:54)
```

I think it was introduced with 2ece25a086e2f97e6f2243aaeed34798f8fc32a7 - @sjaakd, could you check out what exactly is wrong there? Perhaps you find a workaround?

**Comment by sjaakd** [comment]
waiting for the integrationtest on Jenkins...

**Comment by sjaakd** [comment]
and... closed

**Comment by agudian** [comment]
Great, thanks!
