### ISSUE TITLE
IndexOutOfBoundsException when mapping 2 arrays

### ISSUE THREAD

**Issue by lukaszostaniewicz** [mapstruct/mapstruct#577]
Hi, 
```
public class A {
    protected int[] a;
    protected int[] b;
(+ getters/setters)
}
```
```
public class B {
    protected List<Integer> a;
    protected List<Integer> b;
(+ getters/setters)
}
```
```
@Mapper
public interface AtoBMapper {
    public B map(A source);
}
```
<artifactId>mapstruct-processor</artifactId>
 <version>1.0.0.CR1</version>

When classes contain 1 array/list only the mapping generated looks fine. 
When classes contain 2 arrays/lists as in the example above then the mapping generation leads to

AtoBMapper.java:6: error: Internal error in the mapping processor: 

```
java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:3212)   at org.mapstruct.ap.internal.model.IterableMappingMethod.equals(IterableMappingMethod.java:305)        
 at java.util.ArrayList.indexOf(ArrayList.java:298)      at java.util.ArrayList.contains(Array
List.java:281)         
 at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapOrIterableMapping(PropertyMapping.java:484)   
 at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:195)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:426)         
 at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:127)          
 at org.mapstruct.ap.internal.
processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:349)   
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)      
at org.mapstruct.ap.internal.processor.MapperCreationProcesso
r.process(MapperCreationProcessor.java:114)     
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)         
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:220)         
at org.mapstruct.ap.M
appingProcessor.processMapperTypeElement(MappingProcessor.java:200)     
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)         
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:79
3)      
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)   
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)    
at com.sun.tools.java
c.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)         
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)         
at com.sun.tools.javac.main.JavaCompiler.proc
essAnnotations(JavaCompiler.java:1108)          at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)         
at com.sun.tools.javac.main.Main.compile(Main.java:439)         
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
        at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.executeWithExceptionsHandled(AbstractAnnotationProcessorMojo.java:545)        
		at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.jav
a:285)          at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)    
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)      
at org.apache.maven.lifecycle.internal.MojoExecutor.e
xecute(MojoExecutor.java:153)   
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)      
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)     
at org.apache.maven.lifecycle
.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)   
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)        
at org.apache.maven.lifecycle.internal.LifecycleStart
er.execute(LifecycleStarter.java:120)   
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)       
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)         
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)     at org.apache
.maven.cli.MavenCli.doMain(MavenCli.java:216)   at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)        
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)          
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:
57)     
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    
at java.lang.reflect.Method.invoke(Method.java:606)         
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)          
at or
g.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)       
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)        
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
public interface AtoBMapper {
```

**Comment by gunnarmorling** [comment]
Thanks for the report. Would you be interested in providing a fix for this?

**Comment by lukaszostaniewicz** [comment]
```
@Mapper
public interface AtoBMapper {
    public B map(A source);
    List<Integer> map(int[] source); //seems to workaround the issue. 
}
```

**Comment by gunnarmorling** [comment]
Ah yes, that makes sense. That way the code for "forging" the iterable
mapping method isn't executed which triggers that exception.

**Comment by agudian** [comment]
The fix by @vgt-tomek was pushed to master.
