### ISSUE TITLE
NPE when calling resolveViaMethodAndConversion with update an method

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#590]
I have properties that can't be mapped and only an unsuitable update-method (with return type void). Then I get this exception instead of the "Can't map property ..." message.

```
java.lang.NullPointerException
    at org.mapstruct.ap.internal.model.source.MethodMatcher.matchSourceType(MethodMatcher.java:152)
    at org.mapstruct.ap.internal.model.source.MethodMatcher.matches(MethodMatcher.java:121)
    at org.mapstruct.ap.internal.model.source.SourceMethod.matches(SourceMethod.java:482)
    at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingMethods(TypeSelector.java:44)
    at org.mapstruct.ap.internal.model.source.selector.MethodSelectors.getMatchingMethods(MethodSelectors.java:61)
    at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getBestMatch(MappingResolverImpl.java:437)
    at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.resolveViaMethod(MappingResolverImpl.java:263)
    at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.resolveViaMethodAndConversion(MappingResolverImpl.java:394)
    at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:234)
    at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:147)
    at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:115)
    at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:180)
    at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:426)
    at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:127)
    at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:349)
    at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)
    at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114)
    at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)
    at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:220)
```

**Comment by sjaakd** [comment]
@agudian : is this a duplication of https://github.com/mapstruct/mapstruct/issues/488 ?

**Comment by agudian** [comment]
Well, if that issue was resolved, we wouldn't have this problem here. The PR for this just adds a safeguard so we don't get the NPE. It doesn't add any of the new features described in #488. We can leave that to happen for the 1.1 release :wink:

**Comment by sjaakd** [comment]
> Well, if that issue was resolved, we wouldn't have this problem here.

... Just checking :smile:. I guessed we covered that topic already there somewhere. Bit too much distraction.

**Comment by gunnarmorling** [comment]
Done.
