### ISSUE TITLE
NullPointerException using Mapstruct within eclipse + M2E

### ISSUE THREAD

**Issue by dziegenbalg** [mapstruct/mapstruct#655]
The following error occured in a maven-project within eclipse (build via maven is working):

Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.model.source.MethodMatcher.isWithinBounds(MethodMatcher.java:395)  	at org.mapstruct.ap.internal.model.source.MethodMatcher.matches(MethodMatcher.java:138)  	at org.mapstruct.ap.internal.model.source.SourceMethod.matches(SourceMethod.java:482)  	at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingMethods(TypeSelector.java:44)  	at org.mapstruct.ap.internal.model.source.selector.MethodSelectors.getMatchingMethods(MethodSelectors.java:61)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getBestMatch(MappingResolverImpl.java:437)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.resolveViaMethod(MappingResolverImpl.java:263)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:189)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:147)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:115)  	at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:180)  	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:426)  	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:127)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:349)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:220)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:200)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)  	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)  	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:967)  	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:489)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:395)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:331)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:332)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:136)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)  	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)  	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)  	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)  	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)  	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)  	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)  	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by sjaakd** [comment]
@dziegenbalg : can you add a reproducer to this issue?

**Comment by dziegenbalg** [comment]
It's wasn't a simple task to extract the mappings we use. But I solved it. Look at the attached maven-project, import it in eclipse (enable annotation processing) and enjoy :)
Ooops, how can I attach an archive?

**Comment by agudian** [comment]
Yeah, those can be tricky to reproduce. All the better that you found a way! 
You could just create a git repo here on github and push your sample there.

**Comment by dziegenbalg** [comment]
Ook, repo created. Please checkout sample testmapstruct from https://github.com/dziegenbalg/mapstruct.

**Comment by sjaakd** [comment]
Check.. reproducer works. Its this Eclipse compiler again.. The Maven build works, right?

**Comment by dziegenbalg** [comment]
Yeah, maven build works.

**Comment by gunnarmorling** [comment]
Running your test case (thanks for that), I actually get no NPE but the same error as in #644. Could you double-check whether you really see the NPE with this set-up? Or maybe the test case does not exactly represent your original situation?

**Comment by dziegenbalg** [comment]
Hi,

see the attached image. I already see this NPE with the acual eclipse 4.5.1.

![eclipse](https://cloud.githubusercontent.com/assets/15016192/11086594/ed424384-8852-11e5-8365-b65e5f67936a.jpg)

**Comment by sjaakd** [comment]
@gunnarmorling , @dziegenbalg .. I reproduced it as well based on the example of @dziegenbalg . Somehow @agudian and myself concluded already that this was #644 . We somehow (forgot) to report back on this one.

**Comment by gunnarmorling** [comment]
@sjaakd So will this issue be resolved once @agudian's fix for #644 is in?

**Comment by agudian** [comment]
> @sjaakd So will this issue be resolved once @agudian's fix for #644 is in?

Unfortunately not. I took a quick look and I think I identified what seems to be the problem. When collecting the methods of a type (including the superclasses), we check if a method is already overridden in a sub-class (`Executables.wasNotYetOverridden`).

In the example project, there are these types:
```java
public abstract class AbstractMapper<E extends AbstractClass> {
    public abstract <T extends AbstractClass> E toFeKlasse(final T obj);
}
public class EnumClassMapper extends AbstractMapper<EnumClass> {
    @Override
    public <U extends AbstractClass> EnumClass toFeKlasse(final U obj) {
        return obj == null ? null : EnumClass.toEnum( obj.getKey() );
    }
}
@Mapper(uses = EnumClassMapper.class)
public abstract class AMapper { 
...
}
```

When collecting the methods in `EnumClassMapper`, the Eclipse implementation insists that `EnumClassMapper#toFeKlasse(..)` does not override `AbstractMapper#toFeKlasse(..)` when using `Elements#overrides(..)`.

This will then cause some trouble down the road.

I actually don't think that we can fix that on the side within the next days before the 1.0 final. I'd say we push it to a 1.1 or perhaps a 1.0 bugfix release later on... :(

**Comment by gunnarmorling** [comment]
Ok, seems like another bug in the Eclipse APT impl then :(

+1 for looking into a fix for 1.0.1. I don't consider it a blocker for 1.0 as there is the work-around of letting specific mappers not inherit from shared interfaces. I don't think it's needed in most cases as there are typically no polymorphic invocations of mappers. Still of course I hope we can make it work in a sub-sequent release.

**Comment by gunnarmorling** [comment]
Hey @agudian, do you think you could give this one another look?

**Comment by gunnarmorling** [comment]
Need to move that out of 1.1 as there unfortunately is no fix we can implement right now.
