### ISSUE TITLE
@MapperConfig ignored in version 1.0.0.CR2

### ISSUE THREAD

**Issue by darrenreimer** [mapstruct/mapstruct#656]
My common @MapperConfig was working fine in version 1.0.0.CR1, but when I updated to version 1.0.0.CR2, it seems the @MapperConfig is completely ignored.

The @MapperConfig is as follows:
```java
@MapperConfig(
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG,
    collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED
)
public interface MappingCommonConfig {

  @Mappings({
    @Mapping(target = "id", ignore=true),
    @Mapping(target = "recordCreatedBy", ignore=true),
    @Mapping(target = "recordUpdatedBy", ignore=true)
  })
  public DomainObject anyDomainObjectMappingMethod(Object object);
```
It is being referenced as follows:
```java
@Mapper(uses = { CommonMapper.class, CommonCustomMapper.class, CaveatCustomMapper.class }, config = MappingCommonConfig.class)
public abstract class CaveatMapper {
```
All aspects of the mapping configuration seem to be ignored.  Switching back to version 1.0.0.CR1 works fine.  I am running Java 7 and using the spring component model.

**Comment by sjaakd** [comment]
@darrenreimer, did anything else change in the transition? I.e. did you place your `MapperConfig` annotated class in a referenced library?

**Comment by darrenreimer** [comment]
No, I just updated my pom file with the new version and did a Maven update and ran into the issue.  I switched back and forth between CR1 and CR2 and reliably got the issue with CR2, but not CR1.  I'm fairly confident the MappingCommonConfig is being ignored since all my Mapper classes (there are several others besides CaveatMapper) reverted to a ReportingPolicy of warn and my anyDomainObjectMappingMethod() annotations were no longer inherited by any of the mapping methods.

**Comment by darrenreimer** [comment]
Also, if I add the unmappedTargetPolicy, mappingInheritanceStrategy, collectionMappingStrategy configurations to each of the @Mapper classes everything works as it did in CR1, including the anyDomainObjectMappingMethod() method from the MappingCommonConfig being inherited by all mapping methods.

**Comment by agudian** [comment]
I am soooo sure we have tests for that stuff. Could you create a minimal self contained test project so we can see what's different in your case?

**Comment by darrenreimer** [comment]
Yes, I'll do that when I have some time.

**Comment by sjaakd** [comment]
@darrenreimer .. I tried to reproduce it by means of extending your code snippets above..

```java
public class DomainObject {

    private String id;
    private String recordCreatedBy;
    private String recordUpdatedBy;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRecordCreatedBy() {
        return recordCreatedBy;
    }

    public void setRecordCreatedBy(String recordCreatedBy) {
        this.recordCreatedBy = recordCreatedBy;
    }

    public String getRecordUpdatedBy() {
        return recordUpdatedBy;
    }

    public void setRecordUpdatedBy(String recordUpdatedBy) {
        this.recordUpdatedBy = recordUpdatedBy;
    }

}
```

```java
public class MyDomainObject extends DomainObject {

    private String test;

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }
    
}
```

```java
public class MyDomainDto {
    private String test;

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }
}
```

```java
@MapperConfig(
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG,
    collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED
)
public interface MappingCommonConfig {

  @Mappings({
    @Mapping(target = "id", ignore=true),
    @Mapping(target = "recordCreatedBy", ignore=true),
    @Mapping(target = "recordUpdatedBy", ignore=true)
  })
  public DomainObject anyDomainObjectMappingMethod(Object object);
}
```

```java
import org.mapstruct.Mapper;

@Mapper(config = MappingCommonConfig.class)
public abstract class CaveatMapper {

    public abstract MyDomainObject map(MyDomainDto dto);
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>MapStructEx</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.0.0.CR2</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>1.0.0.CR2</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
```

It just works..  So, as @agudian points out, a reproducer / demonstrator from your side would surely help...

**Comment by darrenreimer** [comment]
I have been doing some experimenting with this over the last few days.  This appears to be an Eclipse specific issue as I don't get the error when doing a Maven compile.  After upgrading and doing an 'mvn clean install', the config class seems to be referenced correctly.  However, I get the error below on one or more of my mapper classes (the results do not seem to be consistent).  I can even get the error on the sample you provided.  When the error does occur, the corresponding *MapperImpl class is no longer produced.  Any mapper class I modify after doing an 'mvn clean install' will result in the error and the *MapperImpl class will not be generated so version 1.0.0.CR2 does not seem to be usable in Eclipse, at least not the version of Eclipse that I am using (Kepler R2 with the required Apt M2E Connector 0.0.1.3).  So this issue appears to be the same or similar to #655, #644, #651.  The issue never occurs with 1.0.0.CR1 though.
```
Internal error in the mapping processor: java.lang.IllegalArgumentException: element is not valid for the containing declared type
 at org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:89)
 at org.mapstruct.ap.internal.model.common.TypeFactory.getMethodType(TypeFactory.java:264)
 at org.mapstruct.ap.internal.model.common.TypeFactory.getParameters(TypeFactory.java:281)
 at org.mapstruct.ap.internal.model.common.TypeFactory.getSingleParameter(TypeFactory.java:277)
 at org.mapstruct.ap.internal.model.common.Type.getPropertyWriteAccessors(Type.java:401)
 at org.mapstruct.ap.internal.model.BeanMappingMethod $Builder.souceMethod(BeanMappingMethod.java:95)
 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:357)
 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)
 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114)
 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)
 at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:223)
 at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:203)
 at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:169)
 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
 at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
 at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
 at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
 at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:820)
 at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
 at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:366)
 at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:329)
 at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:303)
 at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:134)
 at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:265)
 at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:193)
 at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
 at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
 at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
 at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
 at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
 at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by agudian** [comment]
@darrenreimer, if that is the exception you get, then you are indeed facing the asMemberOf problem that we have with the Eclipse compiler. And yes, 1.0.0.CR2 is not usable in Eclipse, but AFAIK "only" if you have generics in your mappers or bean types.

Other effects that you might see could have something to do with the old Eclipse version that you use. I'm on Mars SR 1 and it's quite nice - so if you have the option to update, you should try that as well.

Can we close this issue for now? Just create a new issue if you find something more tangible regarding the hick-ups in Eclipse (with an up-to-date version).

**Comment by darrenreimer** [comment]
Yes, my Eclipse install has gotten quite stale and it is probably time for an update.  I definitely do have generics in my mappers so I'll stick with 1.0.0.CR1 for now.  Thanks for the good work on MapStruct.  It has been very useful in completing quite a large mapping task.  I checked my generated mapping implementation classes recently and they are over 10,000 loc so I'm happy I didn't need to write all that.

**Comment by agudian** [comment]
Glad to hear that! You can also give our MapStruct Eclipse plugin a try, it's quite handy for the daily work already - but we still have a lot of ideas for features we haven't implemented, yet... ;)
