### ISSUE TITLE
Mapper with implementationPackage on abstract class not working with componentModel=default

### ISSUE THREAD

**Issue by 0x3333** [mapstruct/mapstruct#660]
I have 2 mappers in the same package. Both annotated with `@Mapper (implementationPackage = "...")`.

When I try to generate the mappers I get the exception:
```
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ web ---
[ERROR] diagnostic: /Users/terciofilho/Workspace/master/web/src/main/java/br/com/web/controller/mapper/AnuncioMapper.java:29: error: Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Attempt to reopen a file for path /Users/terciofilho/Workspace/master/web/target/classes/META-INF/services/br.com.web.controller.mapper.null  
	at org.mapstruct.ap.internal.processor.MapperServiceProcessor.createSourceFile(MapperServiceProcessor.java:92)  
	at org.mapstruct.ap.internal.processor.MapperServiceProcessor.writeToSourceFile(MapperServiceProcessor.java:76)  
	at org.mapstruct.ap.internal.processor.MapperServiceProcessor.process(MapperServiceProcessor.java:62)  
	at org.mapstruct.ap.internal.processor.MapperServiceProcessor.process(MapperServiceProcessor.java:43)  
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:223)  
	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:203)  
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:169)  
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  
	at com.sun.tools.javac.main.Main.compile(Main.java:523)  
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  
	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.executeWithExceptionsHandled(AbstractAnnotationProcessorMojo.java:545)  
	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:285)  
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)  
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)  
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)  
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)  
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)  
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)  
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)  
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)  
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)  
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)  
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)  
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)  
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)  
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)  
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
	at java.lang.reflect.Method.invoke(Method.java:497)  
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)  
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)  
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)  
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: javax.annotation.processing.FilerException: Attempt to reopen a file for path /Users/terciofilho/Workspace/master/web/target/classes/META-INF/services/br.com.web.controller.mapper.null
	at com.sun.tools.javac.processing.JavacFiler.checkFileReopening(JavacFiler.java:535)  
	at com.sun.tools.javac.processing.JavacFiler.createResource(JavacFiler.java:431)  
	at org.mapstruct.ap.internal.processor.MapperServiceProcessor.createSourceFile(MapperServiceProcessor.java:89)  	... 40 more
public abstract class AnuncioMapper extends BasicMapper {
                ^
[ERROR] error on execute: error during compilation
```

If I remove the `implementationPackage` property of @Mapper, no exception is thrown and the mapper is generated correctly.

**Comment by agudian** [comment]
@0x3333, thanks for the report!

Looks like the packageName feature doesn't work with abstract classes when using the `default` component model.

This fix is simple: in `MapperServiceProcessor.getServicesEntry(GeneratedType)`, `getSuperClassName()` must be used if `getInterfaceName() == null`.

We'll fix that for the final version.

**Comment by 0x3333** [comment]
That's cool!

Thanks.

**Comment by agudian** [comment]
Fixed.
