### ISSUE TITLE
Caused by java.lang.ClassNotFoundException: Cannot find implementation for nl.autovooru.android.data.entity.advert.mapper.AdvertMapper

### ISSUE THREAD

**Issue by antslava** [mapstruct/mapstruct#742]
Hi, All.
Sometimes I get ClassNotFoundException. It looks strange because on my Android device all works fine, but when client open application it's rarely crash with such exception. 

```
Fatal Exception: java.lang.IllegalStateException: Fatal Exception was thrown on Scheduler.Worker thread.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ExceptionInInitializerError
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl.lambda$getAdvertFields$35(UserDataRepositoryImpl.java:227)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl.access$lambda$17(UserDataRepositoryImpl.java)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl$$Lambda$20.call(Unknown Source)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:278)
       at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:77)
       at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:56)
       at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:366)
       at rx.Subscriber.setProducer(Subscriber.java:211)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:358)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:55)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.request(OnSubscribeCombineLatest.java:127)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.request(OperatorSubscribeOn.java:88)
       at rx.Subscriber.setProducer(Subscriber.java:209)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1.setProducer(OperatorSubscribeOn.java:81)
       at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:67)
       at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:44)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for nl.autovooru.android.data.entity.advert.mapper.AdvertMapper
       at org.mapstruct.factory.Mappers.getMapper(Mappers.java:98)
       at nl.autovooru.android.data.entity.advert.mapper.AdvertMapper.<clinit>(AdvertMapper.java:23)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl.lambda$getAdvertFields$35(UserDataRepositoryImpl.java:227)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl.access$lambda$17(UserDataRepositoryImpl.java)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl$$Lambda$20.call(Unknown Source)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:278)
       at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:77)
       at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:56)
       at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:366)
       at rx.Subscriber.setProducer(Subscriber.java:211)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:358)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:55)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.request(OnSubscribeCombineLatest.java:127)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.request(OperatorSubscribeOn.java:88)
       at rx.Subscriber.setProducer(Subscriber.java:209)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1.setProducer(OperatorSubscribeOn.java:81)
       at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:67)
       at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:44)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ClassNotFoundException: Cannot find implementation for nl.autovooru.android.data.entity.advert.mapper.AdvertMapper
       at org.mapstruct.factory.Mappers.getMapper(Mappers.java:94)
       at nl.autovooru.android.data.entity.advert.mapper.AdvertMapper.<clinit>(AdvertMapper.java:23)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl.lambda$getAdvertFields$35(UserDataRepositoryImpl.java:227)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl.access$lambda$17(UserDataRepositoryImpl.java)
       at nl.autovooru.android.data.repository.UserDataRepositoryImpl$$Lambda$20.call(Unknown Source)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:278)
       at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:77)
       at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:56)
       at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:366)
       at rx.Subscriber.setProducer(Subscriber.java:211)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:358)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:55)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.request(OnSubscribeCombineLatest.java:127)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.request(OperatorSubscribeOn.java:88)
       at rx.Subscriber.setProducer(Subscriber.java:209)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1.setProducer(OperatorSubscribeOn.java:81)
       at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:67)
       at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:44)
       at rx.Observable.unsafeSubscribe(Observable.java:8098)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

My AdvertMapper looks like

```
@Mapper
public interface AdvertMapper {

    AdvertMapper INSTANCE = Mappers.getMapper(AdvertMapper.class);

    AdvertFields entityToModel(AdvertFieldsEntity entity);

    AutoInfo entityToModel(AutoInfoEntity entity);

    YoutubeInfo entityToModel(YoutubeInfoEntity entity);

    MachineSearchFilters machineSearchFiltersEntityToMachineSearchFilters(MachineSearchFiltersEntity machineSearchFiltersEntity);

    MachineSearchFilters.MainFilters machineMainFiltersEntityToMachineMainFilters(MachineSearchFiltersEntity.MainFiltersEntity mainFiltersEntity);

    MachineFilter machineFilterEntityToMachineFilter(MachineFilterEntity filterEntity);

    MachineSearchFilters.ToggleFilters machineToggleFiltersEntityTomachineToggleFilters(MachineSearchFiltersEntity.ToggleFilters toggleFilters);

    MachineFilter.Options optionsEntityToOptions(MachineFilterEntity.Options optionsEntity);
}

```

So my question is why it happens and how I can fix it. Maybe I do something wrong.

**Comment by vadims** [comment]
We're seeing the same issue on Android as well.

**Comment by gunnarmorling** [comment]
So is this happening one and off for one and the same mapper class?

**Comment by vadims** [comment]
We have 2 mapper classes and it happens to both of them for a very small number of users. We have not been able to reproduce this ourselves.

**Comment by gunnarmorling** [comment]
Ok, I see. Thanks for the quick feedback.

Really odd that it happens intermittently. Could you try and copy the `Mappers` class into your project and adapt it so it's using the classloader of the given `clazz` object? That's the better approach anyways and I've planned to change it into that in the next release.

Would be great to know if that fixes the issue for you.

**Comment by vadims** [comment]
We haven't seen any more crashes after using `ClassLoader classLoader = clazz.getClassLoader();` in `Mappers`.

**Comment by johngamarra** [comment]
I have this issue, any workaround?

**Comment by gunnarmorling** [comment]
@johngamarra See my last comment above for a workaround. We'll change it into this strategy in MapStruct 1.1.

**Comment by antslava** [comment]
Hi All, I think this issues comes from multidex support.
Multidex separate our code to different .dex files, so that's why Mappers classloader can't find *Impl class.
Hello guys @johngamarra , @vadims can you confirm that yours projects use multidex ? Or this issue start reproduce after enabling multidex.

**Comment by vadims** [comment]
Our project only uses multidex for debug builds, however the exceptions were reported from the release builds where multidex was disabled.

**Comment by antslava** [comment]
Can you unpack your release build and check how many dex files you have

**Comment by vadims** [comment]
```bash
--- outputs/apk » zipinfo steller-debug-v1.0.1.apk| grep dex | wc -l
      55
--- outputs/apk » zipinfo steller-v1.0.1.apk| grep dex | wc -l
       1
```

**Comment by antslava** [comment]
thanks, I already get your apk. You are right you have only one dex file.

**Comment by gunnarmorling** [comment]
As of issue #801 we are using the classloader of the given mapper type first now when trying to load the implementation type. This should resolve this issue, too. It's fixed on master, a new Beta containing the fix will be out soon. Going to close this issue therefore. Thanks for all the feedback!
