### ISSUE TITLE
Enable to use MapStruct with JDK 9 Jigsaw

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#744]

**Comment by agudian** [comment]
Pasting a mail from Rory O'Donnell, I guess it's time we get things working in the integration-tests at least.

Hi,
 
* JDK 9 Developer Preview is now available on java.net [1]

Developer Preview milestone: - A reasonably stable build suitable for
broad testing by the developer community is available.
JDK 9 Builds 163 and higher include all planned features.


*Attention annotation processing users and authors - * Request for
feedback on annotation processing API changes made in JDK 9.

As has been done previously during Java SE 7 and Java SE 8, the JSR 269
annotation processing API is undergoing a maintenance review (MR) as
part of Java SE 9. Details of the changes in JDK 9 Early Access build
163 & build 164 available here [2]

Please report experiences running processors under JDK 9 and feedback on
the API changes to the compiler-dev mailing list.
(If you haven’t already subscribed to that list then please do so first,
otherwise your message will be discarded as spam.)

Rgds, Rory

[1] https://jdk9.java.net/download/
[2]
http://mail.openjdk.java.net/pipermail/compiler-dev/2017-April/010896.html

--
Rgds,Rory O'Donnell
Quality Engineering Manager

**Comment by filiphr** [comment]
Here are some pointers about setting up with Travis if we want to have that:

* [JUnit 5 Testing with JDK-9](https://github.com/junit-team/junit5/issues/296) - There are a lot of links there that show how it can be done. Also their [Travis Configuration](https://github.com/junit-team/junit5/blob/master/.travis.yml)
* [Travis JDK-9 Support](https://github.com/travis-ci/travis-ci/issues/5520)

**Comment by gunnarmorling** [comment]
+1 for testing this!

**Comment by gunnarmorling** [comment]
One thing to address is that the @Generated annotation got a
replacement just recently, there is now
javax.annotation.processing.Generated.

**Comment by netmikey** [comment]
JDK9 was released yesterday, so we tried to build our projects with it to see what happens.

First thing happening was that mapstruct generation failed. We're using the Gradle Plugin as described [here](http://mapstruct.org/documentation/installation/#gradle) with the latest Gradle 4.2 and the latest stable MapStruct 1.1.0.Final, but also tested with 1.2.0.CR2 - same result.

The reason is probably that JAXB isn't accessible directly anymore in the modularized JDK9.

Here's the Stacktrace from 1.2.0.CR2:

```
C:\myProject\src\main\java\my\package\MyMapper.java:22: error: Internal error in the mapping processor: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBElement
	at org.mapstruct.ap.internal.model.source.builtin.JaxbElemToValue.<init>(JaxbElemToValue.java:41)       
	at org.mapstruct.ap.internal.model.source.builtin.BuiltInMappingMethods.<init>(BuiltInMappingMethods.java:49)   
	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.<init>(MappingResolverImpl.java:102)        
	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:102)        
	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:80)         
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)         
	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)        
	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)   
	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)        
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)    
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)      
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)       
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)    
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)        
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)    
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)   
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)          
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)     
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)       
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:49)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)       
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)       
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)       
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)       
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)       
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)       
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:204)    
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:189)       
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:121)       
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)       
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)   
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)    
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:179)    
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)         
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)         
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)        
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)      
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)      
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)   
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)      
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)       
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)        
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)       
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)   
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)         
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)       
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)   
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)     
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)   
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)         
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)       
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)         
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)       
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)      
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)      
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)   
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)       
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)     
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)        
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBElement
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
... 76 more
```

**Comment by filiphr** [comment]
This is really strange. We have an explicit check [here](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/BuiltInMappingMethods.java#L49) to see if the type is there and we are getting that it is there from the `TypeFactory` that is why it is being created. However, it seems like the module is not there. I am not sure if this is a bug in the JDK APT itself or it is something else.

We would investigate a bit more about this.

**Comment by agudian** [comment]
That is funny. I tried it a year ago and the `@Generated` annotation was the only thing that caused problems. Finding out that `JAXBElement` is not available worked correctly by then...
Anyway, I had a branch somewhere that prepared running the ITs with Java9 as well... I'll hope to find some time the week after this to make that branch work again with the JDK 9 final.

**Comment by filiphr** [comment]
I was just playing with Java 9 and processors. When the source version is Java 9 then the `JAXBElement` will not be present (if the module is not there). However it looks like you are staying with source version 8 and thus the `JAXBElement` class is there and we are going to try to use it.

@agudian Do you think that we need to check the classes presence somehow differently? And another point we are using other modules (`javax.xml.datatype`) as well (for the XML calendars). Should we add a check for those as well for the `1.2.0.Final` release?

**Comment by gunnarmorling** [comment]
>  Should we add a check for those as well for the 1.2.0.Final release?

I didn't check out the details, but it'd be nice for the Final to be usable
on Java 9. I've done my fair share of working around Java 9 issues for
Hibernate, so if there's anything I can help with, please let me know :)

**Comment by filiphr** [comment]
I have some ideas about how to solve the issues I would prepare a PR for that. I would appreciate if you can review it @gunnarmorling.
