### ISSUE TITLE
@MapperConfig, @InheritConfiguration and java.lang.Object throws Exception

### ISSUE THREAD

**Issue by remmeier** [mapstruct/mapstruct#960]
I try to use @InheritConfiguration to ignore an attribute in multple mappers.

- Interface I with attribute "attr"
- Mapper for X => S
- Mapper for Y => U
- S and U implement I
- X and Y do not implement I and do not have "attr"

Now I would like to ignore A for both mappers with @InheritConfiguration and @MapperConfig. My mapper configuration looks like:

```
public class S {
	private String otherAttr;
	public String getOtherAttr() {
		return otherAttr;
	}
	public void setOtherAttr(String otherAttr) {
		this.otherAttr = otherAttr;
	}
}
public interface I {
	String getAttr();
	void setAttr(String value);
}
public class X implements I {
	private String attr;
	@Override
	public String getAttr() {
		return attr;
	}
	@Override
	public void setAttr(String value) {
		this.attr = value;
	}
}
@MapperConfig
public interface IMapperConfig {

	@Mapping(target = "attr", ignore = true)
	I unmap(Object source);
}
@Mapper(componentModel = "cdi", uses = { IMapperConfig.class })
public interface XMapper {

	@InheritConfiguration
	X map(S source);
}
```

With java.lang.Object as parameter in the MapperConfig any mapper that maps to I should no longer map "attr".

1.1.0-CR2 throws:

```
C:\projects\moap\moap-movie-be\moap-movie-directory-web\src\main\java\test\XMapper.java:7: error: Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.model.source.MappingOptions.applyInheritedOptions(MappingOptions.java:166)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.mergeInheritedOptions(MapperCreationProcessor.java:413)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:263)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:146)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:117)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:270)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:250)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:216)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:155)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	at com.sun.tools.javac.main.Main.compile(Main.java:523)  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)  	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)  	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)  	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:189)  	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:170)  	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:113)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:497)  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:158)  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)  	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)  	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)  	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)  	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)  	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)  	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)  	at java.lang.Thread.run(Thread.java:745)  
public interface XMapper {
       ^
1 error
```

In real life it are dozens of such mappers and multiple attributes we would like to ignore once globally.

**Comment by filiphr** [comment]
@remmeier The problem is that you are using `@Mapping(uses = { IMapperConfig.class })` instead of `@Mapping(config = IMapperConfig.class)`.

**uses** means other mapper types that need to be used by the mapper to create the mappings, whereas **config** is just a configuration which MapStruct will use to create the implementation.

**Comment by sjaakd** [comment]
@filiphr : agreed. Still we should not throw an NPE but have a good error message :wink:. @remmeier : can you confirm the approach of @filiphr works?

**Comment by remmeier** [comment]
yes, thank you, works fine this way. Something other than the NPE would be great.
